# Generated by Django 5.0.6 on 2024-05-29 08:56

import django.db.models.deletion
import lamidb.base.users
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0052_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureset",
            name="hash",
            field=models.CharField(
                db_index=True, default=None, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="paramvalue",
            name="created_by",
            field=models.ForeignKey(
                default=lamidb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="created_by",
            field=models.ForeignKey(
                default=lamidb.base.users.current_user_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="created_by",
            field=models.ForeignKey(
                default=lamidb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                to="lamindb.user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featurevalue",
            unique_together={("feature", "value")},
        ),
        migrations.AlterUniqueTogether(
            name="paramvalue",
            unique_together={("param", "value")},
        ),
    ]
