# Generated by Django 5.1 on 2024-06-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lamindb",
            "0053_alter_featureset_hash_alter_paramvalue_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="previous_runs",
            field=models.ManyToManyField(related_name="+", to="lamindb.run"),
        ),
        migrations.AlterField(
            model_name="param",
            name="previous_runs",
            field=models.ManyToManyField(related_name="+", to="lamindb.run"),
        ),
        migrations.AlterField(
            model_name="storage",
            name="previous_runs",
            field=models.ManyToManyField(related_name="+", to="lamindb.run"),
        ),
        migrations.AlterField(
            model_name="ulabel",
            name="previous_runs",
            field=models.ManyToManyField(related_name="+", to="lamindb.run"),
        ),
    ]
