# Generated by Django 5.1 on 2024-07-26 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0055_artifact_type_artifactparamvalue_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artifactulabel",
            old_name="ulabel_ref_is_name",
            new_name="label_ref_is_name",
        ),
        migrations.RenameField(
            model_name="collectionulabel",
            old_name="ulabel_ref_is_name",
            new_name="label_ref_is_name",
        ),
    ]
