# Generated by Django 5.2 on 2024-08-08 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0060_alter_artifact__actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="meta_artifact",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="_meta_of_collection",
                to="lamindb.artifact",
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="environment",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="_environment_of",
                to="lamindb.artifact",
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="report",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="_report_of",
                to="lamindb.artifact",
            ),
        ),
    ]
