# Generated by Django 5.2 on 2024-08-12 07:46

from django.db import migrations, models


# data migration comes in the next migration due to pending triggers
class Migration(migrations.Migration):
    dependencies = [
        (
            "lamindb",
            "0061_alter_collection_meta_artifact_alter_run_environment_and_more",
        ),
    ]

    operations = [
        # add the field
        migrations.AddField(
            model_name="artifact",
            name="is_latest",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="is_latest",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="transform",
            name="is_latest",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
