# Generated by Django 5.2 on 2024-08-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lnschema_core", "0063_populate_latest_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="version",
            field=models.CharField(
                db_index=True, default=None, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="version",
            field=models.CharField(
                db_index=True, default=None, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="version",
            field=models.CharField(
                db_index=True, default=None, max_length=30, null=True
            ),
        ),
    ]
