# Generated by Django 5.2 on 2024-09-08 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "lnschema_core",
            "0064_alter_artifact_version_alter_collection_version_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="feature_sets",
        ),
        migrations.DeleteModel(
            name="CollectionFeatureSet",
        ),
    ]
