# Generated by Django 5.2 on 2025-01-05 11:58

from django.db import migrations
from django.db.models import F


def transfer_source_code(apps, schema_editor):
    from lamindb._finish import notebook_to_script

    Transform = apps.get_model("lamindb", "Transform")
    transforms = Transform.objects.filter(
        _source_code_artifact__isnull=False,
    ).select_related("_source_code_artifact")

    for transform in transforms:
        print(f"migrating source code of transform {transform}")
        artifact = transform._source_code_artifact

        if artifact.suffix == ".ipynb":
            transform.source_code = notebook_to_script(transform, artifact.path)
        else:
            transform.source_code = artifact.cache().read_text()

        transform._source_code_artifact = None
        transform.save()
        artifact.delete(permanent=True)


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0069_squashed"),
    ]

    operations = [
        migrations.RunPython(transfer_source_code),
        migrations.RemoveField(
            model_name="transform",
            name="_source_code_artifact",
        ),
    ]
