# Generated by Django 5.2 on 2025-01-05 11:58

import django.db.models.deletion
from django.db import migrations, models

import lamindb.base.fields


def transfer_source_code(apps, schema_editor):
    from lamindb._finish import notebook_to_script

    Transform = apps.get_model("lamindb", "Transform")
    transforms = Transform.objects.filter(
        _source_code_artifact__isnull=False,
    ).select_related("_source_code_artifact")

    for transform in transforms:
        print(f"migrating source code of transform {transform}")
        artifact = transform._source_code_artifact

        if artifact.suffix == ".ipynb":
            transform.source_code = notebook_to_script(transform, artifact.path)
        else:
            transform.source_code = artifact.cache().read_text()
        transform.hash = artifact.hash

        transform._source_code_artifact = None
        transform.save()
        artifact.delete(permanent=True)


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0069_squashed"),
    ]

    operations = [
        # changes to transform
        migrations.RunPython(transfer_source_code),
        migrations.RemoveField(
            model_name="transform",
            name="_source_code_artifact",
        ),
        # prepare removal of legacy description field
        migrations.RunSQL(
            sql="""
                UPDATE lamindb_transform
                SET name = name || ' ' || description
                WHERE description IS NOT NULL
                AND description != '';
            """
        ),
        migrations.RemoveField(
            model_name="transform",
            name="description",
        ),
        migrations.RenameField(
            model_name="transform",
            old_name="name",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="transform",
            name="key",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="description",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE lamindb_transform
                SET key = description
                WHERE key IS NULL and description IS NOT NULL;
            """
        ),
        # visibility -> _branch_code
        migrations.RenameField(
            model_name="collection",
            old_name="name",
            new_name="key",
        ),
        migrations.AlterField(
            model_name="collection",
            name="key",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255
            ),
        ),
        # visibility -> _branch_code
        migrations.RenameField(
            model_name="artifact",
            old_name="visibility",
            new_name="_branch_code",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="visibility",
            new_name="_branch_code",
        ),
        migrations.AlterField(
            model_name="artifact",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name="collection",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="feature",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="featureset",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="param",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="run",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="storage",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="transform",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="ulabel",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="_branch_code",
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
        # fix dtype values
        migrations.RunSQL(
            sql="""
                UPDATE lamindb_feature
                SET dtype = 'num'
                WHERE dtype = 'number'
            """
        ),
        migrations.RunSQL(
            sql="""
                UPDATE lamindb_featureset
                SET dtype = 'num'
                WHERE dtype = 'number'
            """
        ),
        # an aux field on Record
        migrations.AddField(
            model_name="artifact",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="featureset",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="param",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="storage",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="transform",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="ulabel",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="aux",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.RenameField(
            model_name="run",
            old_name="is_consecutive",
            new_name="_is_consecutive",
        ),
        migrations.AddField(
            model_name="run",
            name="_status_code",
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="transform",
            name="_template",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="_derived_from",
                to="lamindb.transform",
            ),
        ),
        migrations.RenameField(
            model_name="artifact",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="artifact",
            old_name="_accessor",
            new_name="otype",
        ),
        migrations.AddField(
            model_name="run",
            name="_logfile",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="_logfile_of",
                to="lamindb.artifact",
            ),
        ),
    ]
