# Generated by Django 5.2 on 2025-01-05 11:58

from django.db import migrations

import lamindb.base.fields


def transfer_source_code(apps, schema_editor):
    from lamindb._finish import notebook_to_script

    Transform = apps.get_model("lamindb", "Transform")
    transforms = Transform.objects.filter(
        _source_code_artifact__isnull=False,
    ).select_related("_source_code_artifact")

    for transform in transforms:
        print(f"migrating source code of transform {transform}")
        artifact = transform._source_code_artifact

        if artifact.suffix == ".ipynb":
            transform.source_code = notebook_to_script(transform, artifact.path)
        else:
            transform.source_code = artifact.cache().read_text()

        transform._source_code_artifact = None
        transform.save()
        artifact.delete(permanent=True)


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0069_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="_page_md",
            field=lamindb.base.fields.TextField(
                blank=True, db_default=None, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="_page_md",
            field=lamindb.base.fields.TextField(
                blank=True, db_default=None, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="_page_md",
            field=lamindb.base.fields.TextField(
                blank=True, db_default=None, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="featureset",
            name="_page_md",
            field=lamindb.base.fields.TextField(
                blank=True, db_default=None, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="param",
            name="_page_md",
            field=lamindb.base.fields.TextField(
                blank=True, db_default=None, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="_page_md",
            field=lamindb.base.fields.TextField(
                blank=True, db_default=None, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="storage",
            name="_page_md",
            field=lamindb.base.fields.TextField(
                blank=True, db_default=None, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="transform",
            name="_page_md",
            field=lamindb.base.fields.TextField(
                blank=True, db_default=None, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="ulabel",
            name="_page_md",
            field=lamindb.base.fields.TextField(
                blank=True, db_default=None, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="_page_md",
            field=lamindb.base.fields.TextField(
                blank=True, db_default=None, default=None, null=True
            ),
        ),
        migrations.RunPython(transfer_source_code),
        migrations.RemoveField(
            model_name="transform",
            name="_source_code_artifact",
        ),
        migrations.RunSQL(
            sql="""
                UPDATE lamindb_transform
                SET _page_md = description
                WHERE description IS NOT NULL
                AND description != '';
            """
        ),
        migrations.RemoveField(
            model_name="transform",
            name="description",
        ),
        migrations.RenameField(
            model_name="transform",
            old_name="name",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="transform",
            name="key",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="description",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE lamindb_transform
                SET key = description
                WHERE key IS NULL and description IS NOT NULL;
            """
        ),
    ]
