# Generated by Django 5.2 on 2025-01-13 08:12

import django.db.models.deletion
from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0073_merge_ourprojects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ulabel",
            name="is_concept",
        ),
        migrations.AddField(
            model_name="ulabel",
            name="is_type",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="ulabel",
            name="type",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="records",
                to="lamindb.ulabel",
            ),
        ),
        migrations.AlterField(
            model_name="ulabel",
            name="name",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=150
            ),
        ),
    ]
