# Generated by Django 5.2 on 2025-01-13 14:10

import django.db.models.deletion
import lamindb_setup
from django.db import migrations, models

import lamindb.base.fields
import lamindb.base.users
import lamindb.models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0074_lamindbv1_part4"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FeatureSet",
            new_name="Schema",
        ),
        migrations.RenameModel(
            old_name="ArtifactFeatureSet",
            new_name="ArtifactSchema",
        ),
        migrations.RenameField(
            model_name="feature",
            old_name="feature_sets",
            new_name="schemas",
        ),
        migrations.RenameField(
            model_name="artifact",
            old_name="feature_sets",
            new_name="_schemas_m2m",
        ),
        migrations.RenameField(
            model_name="artifactschema",
            old_name="featureset",
            new_name="schema",
        ),
        migrations.RenameModel(
            old_name="FeatureSetFeature",
            new_name="SchemaFeature",
        ),
        migrations.RenameField(
            model_name="schemafeature",
            old_name="featureset",
            new_name="schema",
        ),
        migrations.AddField(
            model_name="artifact",
            name="schema",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifacts",
                to="lamindb.schema",
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="_schemas_m2m",
            field=models.ManyToManyField(
                related_name="_artifacts_m2m",
                through="lamindb.ArtifactSchema",
                to="lamindb.schema",
            ),
        ),
        migrations.AlterField(
            model_name="artifactschema",
            name="artifact",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_links_schema",
                to="lamindb.artifact",
            ),
        ),
        migrations.AlterField(
            model_name="artifactschema",
            name="schema",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="_links_artifact",
                to="lamindb.schema",
            ),
        ),
    ]


if "bionty" in lamindb_setup.settings.instance.modules:
    Migration.dependencies += [
        ("bionty", "0046_alter_cellline__aux_alter_cellmarker__aux_and_more"),
    ]
