# Generated by Django 5.2 on 2025-01-21 12:56

from django.db import migrations

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# lamindb.migrations.0070_lamindbv1_migrate_data
# lamindb.migrations.0071_lamindbv1_migrate_schema
# lamindb.migrations.0073_merge_ourprojects
# lamindb.migrations.0074_lamindbv1_part4
# lamindb.migrations.0077_lamindbv1_part6b


class Migration(migrations.Migration):
    replaces = [
        ("lamindb", "0070_lamindbv1_migrate_data"),
        ("lamindb", "0071_lamindbv1_migrate_schema"),
        ("lamindb", "0072_remove_user__branch_code_remove_user_aux_and_more"),
        ("lamindb", "0073_merge_ourprojects"),
        ("lamindb", "0074_lamindbv1_part4"),
        ("lamindb", "0075_lamindbv1_part5"),
        ("lamindb", "0076_lamindbv1_part6"),
        ("lamindb", "0077_lamindbv1_part6b"),
        ("lamindb", "0078_lamindbv1_part6c"),
        ("lamindb", "0079_alter_rundata_value_json_and_more"),
        ("lamindb", "0080_polish_lamindbv1"),
    ]

    operations = []
