# Generated by Django 5.1.7 on 2025-04-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0090_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                ("seqno", models.AutoField(primary_key=True, serialize=False)),
                ("migration_history_id", models.BigIntegerField()),
                ("id", models.UUIDField()),
                ("table_name", models.CharField(max_length=100)),
                ("record_id", models.BigIntegerField()),
                ("record_data", models.JSONField(null=True)),
                ("event_type", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Edit History",
                "verbose_name_plural": "Edit Histories",
            },
        ),
    ]
