# Generated by Django 5.1.7 on 2025-04-11 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0090_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locked", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="HistoryMigrationState",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("migration_history_id", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="HistoryTableState",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("table_name", models.CharField(max_length=255)),
                ("backfilled", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                ("seqno", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField()),
                ("record_uid", models.CharField(max_length=8, null=True)),
                ("record_data", models.JSONField(null=True)),
                ("event_type", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField()),
                (
                    "migration_history_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lamindb.historymigrationstate",
                    ),
                ),
                (
                    "table_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lamindb.historytablestate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Edit History",
                "verbose_name_plural": "Edit Histories",
            },
        ),
    ]
