# Generated by Django 5.1.7 on 2025-04-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0090_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("table", models.SmallIntegerField()),
                ("operation", models.SmallIntegerField()),
                ("data", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
