# Generated by Django 5.1.7 on 2025-04-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0090_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("table_id", models.SmallIntegerField()),
                ("operation", models.SmallIntegerField()),
                ("record_id", models.BigIntegerField()),
                ("values", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.SmallIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
