# Generated by Django 5.1.7 on 2025-04-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0091_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locked", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
