# Generated by Django 5.2 on 2025-05-11 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0095_remove_rundata_flextable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artifact",
            name="_param_values",
        ),
        migrations.RemoveField(
            model_name="param",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="param",
            name="run",
        ),
        migrations.RemoveField(
            model_name="param",
            name="schemas",
        ),
        migrations.RemoveField(
            model_name="param",
            name="space",
        ),
        migrations.RemoveField(
            model_name="param",
            name="type",
        ),
        migrations.RemoveField(
            model_name="run",
            name="_param_values",
        ),
        migrations.AlterUniqueTogether(
            name="schemaparam",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="schemaparam",
            name="schema",
        ),
    ]
