# Generated by Django 5.2 on 2025-05-25 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0100_branch_alter_artifact__branch_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artifact",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="feature",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="featurevalue",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="record",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="recordrecord",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="reference",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="run",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="schema",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="sheet",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="storage",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="transform",
            old_name="_branch_code",
            new_name="branch",
        ),
        migrations.RenameField(
            model_name="ulabel",
            old_name="_branch_code",
            new_name="branch",
        ),
    ]
