# Generated by Django 5.2 on 2025-05-25 14:27

from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0101_rename__branch_code_artifact_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                db_default="M",
                db_index=True,
                default="M",
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                db_default="A",
                db_index=True,
                default="A",
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
    ]
