# Generated by Django 5.2 on 2025-05-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0101_alter_artifact_hash_alter_feature_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writelog",
            name="record_uid",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
