# Generated by Django 5.2 on 2025-05-29 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0102_squashed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="writelog",
            name="migration_state",
        ),
        migrations.RemoveField(
            model_name="writelog",
            name="table",
        ),
        migrations.RemoveField(
            model_name="writelog",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="writelog",
            name="space",
        ),
        migrations.DeleteModel(
            name="WriteLogLock",
        ),
        migrations.DeleteModel(
            name="MigrationState",
        ),
        migrations.DeleteModel(
            name="TableState",
        ),
        migrations.DeleteModel(
            name="WriteLog",
        ),
    ]
