# Generated by Django 5.2 on 2025-06-02 10:53

from django.db import migrations

import lamindb.base.fields
import lamindb.base.uids


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0103_remove_writelog_migration_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                db_index=True,
                default=lamindb.base.uids.base62_12,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
    ]
