# Generated by Django 5.2 on 2025-07-03 19:59

import django.db.models.deletion
from django.db import migrations, models

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0108_remove_record_sheet_remove_sheetproject_sheet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="input_of_runs",
            field=models.ManyToManyField(
                related_name="input_records", to="lamindb.run"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="run",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="output_records",
                to="lamindb.run",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recordrecord",
            unique_together={("record", "feature", "value")},
        ),
        migrations.AlterUniqueTogether(
            name="recordrun",
            unique_together={("record", "feature", "value")},
        ),
        migrations.AlterUniqueTogether(
            name="recordulabel",
            unique_together={("record", "feature", "value")},
        ),
    ]
