# Generated by Django 5.2 on 2025-07-01 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0108_remove_record_sheet_remove_sheetproject_sheet_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={},
        ),
        migrations.AlterModelOptions(
            name="space",
            options={},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
