# Generated by Django 5.2 on 2025-07-04 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0110_rename_values_artifacts_record_linked_artifacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="_sort_order",
        ),
    ]
