# Generated by Django 5.2 on 2025-07-27 15:18

import django.core.validators
from django.conf import settings as django_settings
from django.db import migrations, models

import lamindb.base.fields
import lamindb.base.uids


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0117_fix_artifact_storage_hash_unique_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="description",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="hash",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, editable=False, max_length=22, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="key",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="kind",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="otype",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="suffix",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, editable=False, max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=lamindb.base.fields.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="hash",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=22, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="key",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="reference",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="reference_type",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                default=lamindb.base.uids.base62_20,
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="description",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="dtype",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                default=lamindb.base.uids.base62_12,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="unit",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="abbr",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                default=lamindb.base.uids.base62_12,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="abbr",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="description",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="doi",
            field=lamindb.base.fields.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a DOI (e.g., 10.1000/xyz123 or https://doi.org/10.1000/xyz123)",
                        regex="^(?:https?://(?:dx\\.)?doi\\.org/|doi:|DOI:)?10\\.\\d+/.*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="name",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="text",
            field=lamindb.base.fields.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                default=lamindb.base.uids.base62_12,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="url",
            field=lamindb.base.fields.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transform",
            name="description",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="hash",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=22, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="key",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="reference",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="reference_type",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="type",
            field=lamindb.base.fields.CharField(
                blank=True, default="pipeline", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, editable=False, max_length=16, unique=True
            ),
        ),
    ]


POSTGRES_OPERATIONS = [
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(fields=["uid"], name="lamindb_artifact_uid_std_idx"),
    ),
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(fields=["key"], name="lamindb_artifact_key_std_idx"),
    ),
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(
            fields=["description"], name="lamindb_artifact_description_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(fields=["suffix"], name="lamindb_artifact_suffix_std_idx"),
    ),
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(fields=["kind"], name="lamindb_artifact_kind_std_idx"),
    ),
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(fields=["otype"], name="lamindb_artifact_otype_std_idx"),
    ),
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(fields=["hash"], name="lamindb_artifact_hash_std_idx"),
    ),
    migrations.AddIndex(
        model_name="collection",
        index=models.Index(fields=["uid"], name="lamindb_collection_uid_std_idx"),
    ),
    migrations.AddIndex(
        model_name="collection",
        index=models.Index(fields=["key"], name="lamindb_collection_key_std_idx"),
    ),
    migrations.AddIndex(
        model_name="collection",
        index=models.Index(
            fields=["description"], name="lamindb_collection_description_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="collection",
        index=models.Index(fields=["hash"], name="lamindb_collection_hash_std_idx"),
    ),
    migrations.AddIndex(
        model_name="collection",
        index=models.Index(
            fields=["reference"], name="lamindb_collection_reference_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="collection",
        index=models.Index(
            fields=["reference_type"],
            name="lamindb_collection_reference_type_std_idx",
        ),
    ),
    migrations.AddIndex(
        model_name="feature",
        index=models.Index(fields=["uid"], name="lamindb_feature_uid_std_idx"),
    ),
    migrations.AddIndex(
        model_name="feature",
        index=models.Index(fields=["name"], name="lamindb_feature_name_std_idx"),
    ),
    migrations.AddIndex(
        model_name="feature",
        index=models.Index(fields=["dtype"], name="lamindb_feature_dtype_std_idx"),
    ),
    migrations.AddIndex(
        model_name="feature",
        index=models.Index(fields=["unit"], name="lamindb_feature_unit_std_idx"),
    ),
    migrations.AddIndex(
        model_name="feature",
        index=models.Index(
            fields=["description"], name="lamindb_feature_description_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="feature",
        index=models.Index(
            fields=["synonyms"], name="lamindb_feature_synonyms_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="project",
        index=models.Index(fields=["uid"], name="lamindb_project_uid_std_idx"),
    ),
    migrations.AddIndex(
        model_name="project",
        index=models.Index(fields=["name"], name="lamindb_project_name_std_idx"),
    ),
    migrations.AddIndex(
        model_name="project",
        index=models.Index(fields=["abbr"], name="lamindb_project_abbr_std_idx"),
    ),
    migrations.AddIndex(
        model_name="project",
        index=models.Index(fields=["url"], name="lamindb_project_url_std_idx"),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(fields=["uid"], name="lamindb_reference_uid_std_idx"),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(fields=["name"], name="lamindb_reference_name_std_idx"),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(fields=["abbr"], name="lamindb_reference_abbr_std_idx"),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(fields=["url"], name="lamindb_reference_url_std_idx"),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(fields=["doi"], name="lamindb_reference_doi_std_idx"),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(
            fields=["description"], name="lamindb_reference_description_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(fields=["text"], name="lamindb_reference_text_std_idx"),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(fields=["uid"], name="lamindb_transform_uid_std_idx"),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(fields=["key"], name="lamindb_transform_key_std_idx"),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(
            fields=["description"], name="lamindb_transform_description_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(fields=["type"], name="lamindb_transform_type_std_idx"),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(
            fields=["source_code"], name="lamindb_transform_source_code_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(fields=["hash"], name="lamindb_transform_hash_std_idx"),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(
            fields=["reference"], name="lamindb_transform_reference_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(
            fields=["reference_type"],
            name="lamindb_transform_reference_type_std_idx",
        ),
    ),
]

SQLITE_OPERATIONS = [
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(fields=["uid"], name="lamindb_artifact_uid_std_idx"),
    ),
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(fields=["key"], name="lamindb_artifact_key_std_idx"),
    ),
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(
            fields=["description"], name="lamindb_artifact_description_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(fields=["suffix"], name="lamindb_artifact_suffix_std_idx"),
    ),
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(fields=["kind"], name="lamindb_artifact_kind_std_idx"),
    ),
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(fields=["otype"], name="lamindb_artifact_otype_std_idx"),
    ),
    migrations.AddIndex(
        model_name="artifact",
        index=models.Index(fields=["hash"], name="lamindb_artifact_hash_std_idx"),
    ),
    migrations.AddIndex(
        model_name="collection",
        index=models.Index(fields=["uid"], name="lamindb_collection_uid_std_idx"),
    ),
    migrations.AddIndex(
        model_name="collection",
        index=models.Index(fields=["key"], name="lamindb_collection_key_std_idx"),
    ),
    migrations.AddIndex(
        model_name="collection",
        index=models.Index(
            fields=["description"], name="lamindb_collection_description_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="collection",
        index=models.Index(fields=["hash"], name="lamindb_collection_hash_std_idx"),
    ),
    migrations.AddIndex(
        model_name="collection",
        index=models.Index(
            fields=["reference"], name="lamindb_collection_reference_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="collection",
        index=models.Index(
            fields=["reference_type"],
            name="lamindb_collection_reference_type_std_idx",
        ),
    ),
    migrations.AddIndex(
        model_name="feature",
        index=models.Index(fields=["uid"], name="lamindb_feature_uid_std_idx"),
    ),
    migrations.AddIndex(
        model_name="feature",
        index=models.Index(fields=["name"], name="lamindb_feature_name_std_idx"),
    ),
    migrations.AddIndex(
        model_name="feature",
        index=models.Index(fields=["dtype"], name="lamindb_feature_dtype_std_idx"),
    ),
    migrations.AddIndex(
        model_name="feature",
        index=models.Index(fields=["unit"], name="lamindb_feature_unit_std_idx"),
    ),
    migrations.AddIndex(
        model_name="feature",
        index=models.Index(
            fields=["description"], name="lamindb_feature_description_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="feature",
        index=models.Index(
            fields=["synonyms"], name="lamindb_feature_synonyms_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="project",
        index=models.Index(fields=["uid"], name="lamindb_project_uid_std_idx"),
    ),
    migrations.AddIndex(
        model_name="project",
        index=models.Index(fields=["name"], name="lamindb_project_name_std_idx"),
    ),
    migrations.AddIndex(
        model_name="project",
        index=models.Index(fields=["abbr"], name="lamindb_project_abbr_std_idx"),
    ),
    migrations.AddIndex(
        model_name="project",
        index=models.Index(fields=["url"], name="lamindb_project_url_std_idx"),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(fields=["uid"], name="lamindb_reference_uid_std_idx"),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(fields=["name"], name="lamindb_reference_name_std_idx"),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(fields=["abbr"], name="lamindb_reference_abbr_std_idx"),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(fields=["url"], name="lamindb_reference_url_std_idx"),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(fields=["doi"], name="lamindb_reference_doi_std_idx"),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(
            fields=["description"], name="lamindb_reference_description_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="reference",
        index=models.Index(fields=["text"], name="lamindb_reference_text_std_idx"),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(fields=["uid"], name="lamindb_transform_uid_std_idx"),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(fields=["key"], name="lamindb_transform_key_std_idx"),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(
            fields=["description"], name="lamindb_transform_description_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(fields=["type"], name="lamindb_transform_type_std_idx"),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(
            fields=["source_code"], name="lamindb_transform_source_code_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(fields=["hash"], name="lamindb_transform_hash_std_idx"),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(
            fields=["reference"], name="lamindb_transform_reference_std_idx"
        ),
    ),
    migrations.AddIndex(
        model_name="transform",
        index=models.Index(
            fields=["reference_type"],
            name="lamindb_transform_reference_type_std_idx",
        ),
    ),
]

db_engine = django_settings.DATABASES["default"]["ENGINE"]
if "postgresql" in db_engine:
    Migration.operations += POSTGRES_OPERATIONS
else:
    Migration.operations += SQLITE_OPERATIONS
