# Generated by Django 5.2 on 2025-07-27 15:18

from django.contrib.postgres.operations import TrigramExtension
from django.db import connection, migrations


def apply_trigram_extension(apps, schema_editor):
    if connection.vendor == "postgresql":
        TrigramExtension().database_forwards(apps, schema_editor, None, None)


def revert_trigram_extension(apps, schema_editor):
    if connection.vendor == "postgresql":
        TrigramExtension().database_backwards(apps, schema_editor, None, None)


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0117_fix_artifact_storage_hash_unique_constraints"),
    ]

    operations = [
        migrations.RunPython(apply_trigram_extension, revert_trigram_extension)
    ]
