# Generated by Django 5.2 on 2025-07-27 15:18

import django.core.validators
from django.conf import settings as django_settings
from django.db import migrations, models

import lamindb.base.fields
import lamindb.base.uids


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0118_install_pg_trgm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="description",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="hash",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, editable=False, max_length=22, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="key",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="kind",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="otype",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, editable=False, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="suffix",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, editable=False, max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=lamindb.base.fields.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="hash",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=22, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="key",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="reference",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                default=lamindb.base.uids.base62_20,
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="description",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="dtype",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="name",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                default=lamindb.base.uids.base62_12,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="unit",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="abbr",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                default=lamindb.base.uids.base62_12,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="abbr",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="description",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="doi",
            field=lamindb.base.fields.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be a DOI (e.g., 10.1000/xyz123 or https://doi.org/10.1000/xyz123)",
                        regex="^(?:https?://(?:dx\\.)?doi\\.org/|doi:|DOI:)?10\\.\\d+/.*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="name",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="text",
            field=lamindb.base.fields.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                default=lamindb.base.uids.base62_12,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="url",
            field=lamindb.base.fields.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transform",
            name="description",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="hash",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=22, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="key",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="reference",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="type",
            field=lamindb.base.fields.CharField(
                blank=True, default="pipeline", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, editable=False, max_length=16, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="name",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="reference",
            field=lamindb.base.fields.CharField(
                blank=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                default=lamindb.base.uids.base62_16,
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]


db_engine = django_settings.DATABASES["default"]["ENGINE"]
if "postgresql" in db_engine:
    POSTGRES_OPERATIONS = [
        migrations.AddIndex(
            model_name="artifact",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("uid"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_artifac_uid_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("key"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_artifac_key_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("description"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_artifac_descrip_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("suffix"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_artifac_suffix_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("kind"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_artifac_kind_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("otype"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_artifac_otype_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("hash"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_artifac_hash_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("uid"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_collect_uid_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("key"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_collect_key_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("description"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_collect_descrip_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("hash"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_collect_hash_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("reference"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_collect_referen_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("uid"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_feature_uid_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("name"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_feature_name_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("dtype"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_feature_dtype_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("unit"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_feature_unit_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("description"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_feature_descrip_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("synonyms"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_feature_synonym_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("uid"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_project_uid_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("name"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_project_name_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("abbr"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_project_abbr_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("url"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_project_url_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("uid"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_referen_uid_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("name"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_referen_name_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("abbr"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_referen_abbr_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("url"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_referen_url_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("doi"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_referen_doi_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("description"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_referen_descrip_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("text"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_referen_text_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("uid"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_transfo_uid_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("key"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_transfo_key_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("description"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_transfo_descrip_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("type"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_transfo_type_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("source_code"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_transfo_source__tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("hash"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_transfo_hash_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("reference"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_transfo_referen_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("uid"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_run_uid_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("name"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_run_name_tgmidx",
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Lower(
                        django.db.models.functions.comparison.Coalesce(
                            models.F("reference"), models.Value("")
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="lamindb_run_referen_tgmidx",
            ),
        ),
    ]
    Migration.operations += POSTGRES_OPERATIONS
else:
    SQLITE_OPERATIONS = [
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(fields=["uid"], name="lamindb_artifac_uid_idx"),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(fields=["key"], name="lamindb_artifac_key_idx"),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["description"], name="lamindb_artifac_descrip_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(fields=["suffix"], name="lamindb_artifac_suffix_idx"),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(fields=["kind"], name="lamindb_artifac_kind_idx"),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(fields=["otype"], name="lamindb_artifac_otype_idx"),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(fields=["hash"], name="lamindb_artifac_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(fields=["uid"], name="lamindb_collect_uid_idx"),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(fields=["key"], name="lamindb_collect_key_idx"),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["description"], name="lamindb_collect_descrip_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(fields=["hash"], name="lamindb_collect_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["reference"], name="lamindb_collect_referen_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(fields=["uid"], name="lamindb_feature_uid_idx"),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(fields=["name"], name="lamindb_feature_name_idx"),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(fields=["dtype"], name="lamindb_feature_dtype_idx"),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(fields=["unit"], name="lamindb_feature_unit_idx"),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(
                fields=["description"], name="lamindb_feature_descrip_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(fields=["synonyms"], name="lamindb_feature_synonym_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["uid"], name="lamindb_project_uid_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["name"], name="lamindb_project_name_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["abbr"], name="lamindb_project_abbr_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["url"], name="lamindb_project_url_idx"),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(fields=["uid"], name="lamindb_referen_uid_idx"),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(fields=["name"], name="lamindb_referen_name_idx"),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(fields=["abbr"], name="lamindb_referen_abbr_idx"),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(fields=["url"], name="lamindb_referen_url_idx"),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(fields=["doi"], name="lamindb_referen_doi_idx"),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(
                fields=["description"], name="lamindb_referen_descrip_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reference",
            index=models.Index(fields=["text"], name="lamindb_referen_text_idx"),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=models.Index(fields=["uid"], name="lamindb_transfo_uid_idx"),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=models.Index(fields=["key"], name="lamindb_transfo_key_idx"),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=models.Index(
                fields=["description"], name="lamindb_transfo_descrip_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=models.Index(fields=["type"], name="lamindb_transfo_type_idx"),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=models.Index(
                fields=["source_code"], name="lamindb_transfo_source__idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=models.Index(fields=["hash"], name="lamindb_transfo_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="transform",
            index=models.Index(
                fields=["reference"], name="lamindb_transfo_referen_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["uid"], name="lamindb_run_uid_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["name"], name="lamindb_run_name_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["reference"], name="lamindb_run_referen_idx"),
        ),
    ]
    Migration.operations += SQLITE_OPERATIONS
