# Generated by Django 5.1.12 on 2025-09-28 20:30

from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0121_recorduser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="people",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="authors",
        ),
        migrations.AlterUniqueTogether(
            name="personproject",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="recordperson",
            unique_together=None,
        ),
        migrations.RenameField(
            model_name="reference",
            old_name="records",
            new_name="linked_in_records",
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=lamindb.base.fields.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="description",
            field=lamindb.base.fields.TextField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="PersonProject",
        ),
        migrations.DeleteModel(
            name="RecordPerson",
        ),
    ]
