# Generated by Django 5.1.12 on 2025-09-29 07:51

from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0125_artifact_is_locked_collection_is_locked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="featurevalue",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="recordrecord",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="schema",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AlterField(
            model_name="ulabel",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
    ]
