# Generated by Django 5.1.12 on 2025-10-01 14:39

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("bionty", "0061_remove_cellline_page_remove_cellmarker_page_and_more"),
        ("lamindb", "0128_artifact__real_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recordrecord",
            name="page",
        ),
        migrations.RemoveField(
            model_name="run",
            name="page",
        ),
        migrations.RemoveField(
            model_name="transform",
            name="page",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="page",
        ),
        migrations.RemoveField(
            model_name="schema",
            name="page",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="page",
        ),
        migrations.RemoveField(
            model_name="featurevalue",
            name="page",
        ),
        migrations.RemoveField(
            model_name="ulabel",
            name="page",
        ),
        migrations.RemoveField(
            model_name="project",
            name="page",
        ),
        migrations.RemoveField(
            model_name="storage",
            name="page",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="page",
        ),
        migrations.RemoveField(
            model_name="record",
            name="page",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="page",
        ),
        migrations.CreateModel(
            name="ArtifactPage",
            fields=[
                (
                    "version",
                    lamindb.base.fields.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "is_latest",
                    lamindb.base.fields.BooleanField(
                        blank=True, db_index=True, default=True
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("content", models.TextField()),
                ("hash", models.CharField(db_index=True, max_length=22, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        editable=False,
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="lamindb.artifact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="lamindb.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RootPage",
            fields=[
                (
                    "version",
                    lamindb.base.fields.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "is_latest",
                    lamindb.base.fields.BooleanField(
                        blank=True, db_index=True, default=True
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("table_name", models.CharField(db_index=True, max_length=255)),
                ("content", models.TextField()),
                ("hash", models.CharField(db_index=True, max_length=22, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        editable=False,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="lamindb.user",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Page",
        ),
    ]
