# Generated by Django 5.1.12 on 2025-10-04 10:57

from django.db import migrations, models

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0131_record_unique_name_type_space"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="parents",
            field=models.ManyToManyField(related_name="children", to="lamindb.record"),
        ),
        migrations.AddField(
            model_name="record",
            name="reference",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="reference_type",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=25, null=True
            ),
        ),
    ]
