# Generated by Django 5.1.12 on 2025-10-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0132_record_parents_record_reference_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="ulabels",
            new_name="linked_ulabels",
        ),
        migrations.AlterField(
            model_name="record",
            name="linked_ulabels",
            field=models.ManyToManyField(
                related_name="linked_in_records",
                through="lamindb.RecordULabel",
                to="lamindb.ulabel",
            ),
        ),
    ]
