# Generated by Django 5.1.12 on 2025-10-04 13:42

import django.db.models.deletion
from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0132_record_parents_record_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordartifact",
            name="record",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_values_artifact",
                to="lamindb.record",
            ),
        ),
        migrations.AlterField(
            model_name="recordjson",
            name="record",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_values_json",
                to="lamindb.record",
            ),
        ),
        migrations.AlterField(
            model_name="recordproject",
            name="record",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_values_project",
                to="lamindb.record",
            ),
        ),
        migrations.AlterField(
            model_name="recordrecord",
            name="record",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_values_record",
                to="lamindb.record",
            ),
        ),
        migrations.AlterField(
            model_name="recordreference",
            name="record",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_values_reference",
                to="lamindb.record",
            ),
        ),
        migrations.AlterField(
            model_name="recordrun",
            name="record",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_values_run",
                to="lamindb.record",
            ),
        ),
        migrations.AlterField(
            model_name="recordulabel",
            name="record",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_values_ulabel",
                to="lamindb.record",
            ),
        ),
        migrations.AlterField(
            model_name="recorduser",
            name="record",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_values_user",
                to="lamindb.record",
            ),
        ),
    ]
