# Generated by Django 5.2 on 2025-10-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0132_record_parents_record_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="params",
            field=models.JSONField(null=True),
        ),
    ]
