# Generated by Django 5.2 on 2025-10-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0135_alter_collection_hash_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="record",
            name="unique_name_type_space",
        ),
        migrations.AddConstraint(
            model_name="feature",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch_id", -1), _negated=True),
                fields=("name", "type", "space"),
                name="unique_feature_name_type_space",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch_id", -1), _negated=True),
                fields=("name", "type", "space"),
                name="unique_project_name_type_space",
            ),
        ),
        migrations.AddConstraint(
            model_name="record",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch_id", -1), _negated=True),
                fields=("name", "type", "space"),
                name="unique_record_name_type_space",
            ),
        ),
        migrations.AddConstraint(
            model_name="reference",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch_id", -1), _negated=True),
                fields=("name", "type", "space"),
                name="unique_reference_name_type_space",
            ),
        ),
        migrations.AddConstraint(
            model_name="schema",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch_id", -1), _negated=True),
                fields=("name", "type", "space"),
                name="unique_schema_name_type_space",
            ),
        ),
        migrations.AddConstraint(
            model_name="ulabel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch_id", -1), _negated=True),
                fields=("name", "type", "space"),
                name="unique_ulabel_name_type_space",
            ),
        ),
    ]
