# Generated by Django 5.1.8 on 2025-10-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lamindb",
            "0137_remove_recordrecord__aux_remove_recordrecord_branch_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="linked_users",
        ),
        migrations.AddField(
            model_name="user",
            name="linked_in_records",
            field=models.ManyToManyField(
                related_name="linked_users",
                through="lamindb.RecordUser",
                to="lamindb.record",
            ),
        ),
    ]
