# Generated by Django 5.2.7 on 2025-10-29 15:16

from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0138_remove_record_linked_users_user_linked_in_records"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="text",
            field=lamindb.base.fields.TextField(blank=True, default=None, null=True),
        ),
    ]
