# Generated by Django 5.2 on 2025-11-16 12:46

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import lamindb.base.fields
import lamindb.base.users
import lamindb.models.sqlrecord


def migrate_predecessor_data(apps, schema_editor):
    """Migrate data from old M2M to new through model."""
    apps.get_model("lamindb", "Transform")
    TransformTransform = apps.get_model("lamindb", "TransformTransform")
    User = apps.get_model("lamindb", "User")

    # Get the old M2M through table data
    # The old table name is typically: lamindb_transform_predecessors
    db_alias = schema_editor.connection.alias

    # Check if old M2M table exists - database agnostic approach
    table_exists = False

    # Use Django's introspection to check if table exists
    from django.db import connection

    with connection.cursor() as cursor:
        table_name = "lamindb_transform_predecessors"
        if table_name in connection.introspection.table_names():
            table_exists = True

    if table_exists:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT from_transform_id, to_transform_id
                FROM lamindb_transform_predecessors
            """)

            # Get current user for created_by field
            try:
                current_user = User.objects.using(db_alias).first()
                user_id = current_user.id if current_user else None
            except Exception:
                user_id = 1

            # Create new through model instances
            # Note: from_transform_id is the successor, to_transform_id is the predecessor
            rows = cursor.fetchall()
            for successor_id, predecessor_id in rows:
                TransformTransform.objects.using(db_alias).create(
                    successor_id=successor_id,
                    predecessor_id=predecessor_id,
                    created_by_id=user_id,
                )


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0141_transform_entrypoint_transform_environment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transform",
            name="environment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_environment_of_transforms",
                to="lamindb.transform",
            ),
        ),
        # Create the through model first
        migrations.CreateModel(
            name="TransformTransform",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("config", models.JSONField(default=None, null=True)),
                (
                    "created_at",
                    lamindb.base.fields.DateTimeField(
                        blank=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                (
                    "created_by",
                    lamindb.base.fields.ForeignKey(
                        blank=True,
                        default=lamindb.base.users.current_user_id,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.user",
                    ),
                ),
                (
                    "predecessor",
                    lamindb.base.fields.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_successor",
                        to="lamindb.transform",
                    ),
                ),
                (
                    "successor",
                    lamindb.base.fields.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_predecessor",
                        to="lamindb.transform",
                    ),
                ),
            ],
            options={
                "unique_together": {("successor", "predecessor")},
            },
            bases=(models.Model, lamindb.models.sqlrecord.IsLink),
        ),
        # Remove the old M2M field
        migrations.RemoveField(
            model_name="transform",
            name="predecessors",
        ),
        # Migrate the data
        migrations.RunPython(
            migrate_predecessor_data,
            reverse_code=migrations.RunPython.noop,
        ),
        # Add the new M2M field with through model
        migrations.AddField(
            model_name="transform",
            name="predecessors",
            field=models.ManyToManyField(
                related_name="successors",
                through="lamindb.TransformTransform",
                to="lamindb.transform",
            ),
        ),
    ]
