# Generated by Django 5.2 on 2025-11-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0142_alter_transform_environment_transformtransform_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transform",
            name="entrypoint",
        ),
        migrations.AddField(
            model_name="transform",
            name="config",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="transform",
            name="is_flow",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="transform",
            name="flow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="lamindb.transform",
            ),
        ),
    ]
