# Generated by Django 5.2 on 2025-11-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0143_remove_transform_entrypoint_transform_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transform",
            name="is_flow",
            field=models.BooleanField(db_default=False, db_index=True, default=False),
        ),
    ]
