# Generated by Django 5.2 on 2025-11-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0144_alter_transform_is_flow"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feature",
            name="unique_feature_name_type_space",
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_project_name_type_space",
        ),
        migrations.RemoveConstraint(
            model_name="record",
            name="unique_record_name_type_space",
        ),
        migrations.RemoveConstraint(
            model_name="reference",
            name="unique_reference_name_type_space",
        ),
        migrations.RemoveConstraint(
            model_name="schema",
            name="unique_schema_name_type_space",
        ),
        migrations.RemoveConstraint(
            model_name="ulabel",
            name="unique_ulabel_name_type_space",
        ),
        migrations.AddConstraint(
            model_name="feature",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("branch_id", -1), _negated=True),
                    ("is_type", True),
                    ("type__isnull", True),
                ),
                fields=("name",),
                name="unique_feature_type_name_at_root",
            ),
        ),
        migrations.AddConstraint(
            model_name="feature",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("branch_id", -1), _negated=True),
                    ("is_type", True),
                    ("type__isnull", False),
                ),
                fields=("name", "type"),
                name="unique_feature_type_name_under_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("branch_id", -1), _negated=True),
                    ("is_type", True),
                    ("type__isnull", True),
                ),
                fields=("name",),
                name="unique_project_type_name_at_root",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("branch_id", -1), _negated=True),
                    ("is_type", True),
                    ("type__isnull", False),
                ),
                fields=("name", "type"),
                name="unique_project_type_name_under_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="record",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("branch_id", -1), _negated=True),
                    ("is_type", True),
                    ("type__isnull", True),
                ),
                fields=("name",),
                name="unique_record_type_name_at_root",
            ),
        ),
        migrations.AddConstraint(
            model_name="record",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("branch_id", -1), _negated=True),
                    ("is_type", True),
                    ("type__isnull", False),
                ),
                fields=("name", "type"),
                name="unique_record_type_name_under_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="reference",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("branch_id", -1), _negated=True),
                    ("is_type", True),
                    ("type__isnull", True),
                ),
                fields=("name",),
                name="unique_reference_type_name_at_root",
            ),
        ),
        migrations.AddConstraint(
            model_name="reference",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("branch_id", -1), _negated=True),
                    ("is_type", True),
                    ("type__isnull", False),
                ),
                fields=("name", "type"),
                name="unique_reference_type_name_under_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="schema",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("branch_id", -1), _negated=True),
                    ("is_type", True),
                    ("type__isnull", True),
                ),
                fields=("name",),
                name="unique_schema_type_name_at_root",
            ),
        ),
        migrations.AddConstraint(
            model_name="schema",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("branch_id", -1), _negated=True),
                    ("is_type", True),
                    ("type__isnull", False),
                ),
                fields=("name", "type"),
                name="unique_schema_type_name_under_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="ulabel",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("branch_id", -1), _negated=True),
                    ("is_type", True),
                    ("type__isnull", True),
                ),
                fields=("name",),
                name="unique_ulabel_type_name_at_root",
            ),
        ),
        migrations.AddConstraint(
            model_name="ulabel",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("branch_id", -1), _negated=True),
                    ("is_type", True),
                    ("type__isnull", False),
                ),
                fields=("name", "type"),
                name="unique_ulabel_type_name_under_type",
            ),
        ),
    ]
