# Generated by Django 5.2.8 on 2025-11-23 09:53

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0146_squashed"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="record",
            trigger=pgtrigger.compiler.Trigger(
                name="update_feature_dtype_on_record_type_name_change",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."name" IS DISTINCT FROM (NEW."name") AND NEW."is_type")',
                    func="DECLARE\n    old_path TEXT;\n    new_path TEXT;\n    pattern TEXT;\nBEGIN\n    -- Build the hierarchical path for OLD name\n    -- This recursively walks up the type hierarchy\n    WITH RECURSIVE record_path AS (\n        -- Start with the changed record\n        SELECT\n            id,\n            name,\n            type_id,\n            name::TEXT AS path,\n            1 as depth\n        FROM lamindb_record\n        WHERE id = OLD.id\n\n        UNION ALL\n\n        -- Recursively build path upwards through parent types\n        SELECT\n            r.id,\n            r.name,\n            r.type_id,\n            r.name || '[' || rp.path || ']' AS path,\n            rp.depth + 1\n        FROM lamindb_record r\n        INNER JOIN record_path rp ON r.id = rp.type_id\n    )\n    SELECT path INTO old_path\n    FROM record_path\n    ORDER BY depth DESC\n    LIMIT 1;\n\n    -- Build the hierarchical path for NEW name\n    WITH RECURSIVE record_path AS (\n        SELECT\n            id,\n            name,\n            type_id,\n            name::TEXT AS path,\n            1 as depth\n        FROM lamindb_record\n        WHERE id = NEW.id\n\n        UNION ALL\n\n        SELECT\n            r.id,\n            r.name,\n            r.type_id,\n            r.name || '[' || rp.path || ']' AS path,\n            rp.depth + 1\n        FROM lamindb_record r\n        INNER JOIN record_path rp ON r.id = rp.type_id\n    )\n    SELECT path INTO new_path\n    FROM record_path\n    ORDER BY depth DESC\n    LIMIT 1;\n\n    -- Update feature dtypes\n    -- We need to ensure we only replace within the cat[Record[...]] context\n    -- and match the exact hierarchical path\n\n    -- Case 1: The path appears at the end (leaf node in hierarchy)\n    -- Matches: cat[Record[ParentA[ChildA]]] or cat[Record[ChildA]]\n    UPDATE lamindb_feature\n    SET dtype = REPLACE(dtype, 'cat[Record[' || old_path || ']', 'cat[Record[' || new_path || ']')\n    WHERE dtype LIKE '%cat[Record[%'\n        AND (\n            dtype LIKE '%cat[Record[' || old_path || ']]%'  -- Direct child of Record\n            OR dtype LIKE '%cat[Record[%[' || old_path || ']]%'  -- Nested under parents\n        );\n\n    -- Case 2: The path has child paths after it (intermediate node in hierarchy)\n    -- Matches: cat[Record[ParentA[ChildA[GrandchildB]]]]\n    UPDATE lamindb_feature\n    SET dtype = REPLACE(dtype, 'cat[Record[' || old_path || '[', 'cat[Record[' || new_path || '[')\n    WHERE dtype LIKE '%cat[Record[%'\n        AND (\n            dtype LIKE '%cat[Record[' || old_path || '[%'  -- Direct child of Record\n            OR dtype LIKE '%cat[Record[%[' || old_path || '[%'  -- Nested under parents\n        );\n\n    RETURN NEW;\nEND;\n",
                    hash="b324b997a996c43f2f6f0d5ec9bf76db48f0e149",
                    operation="UPDATE",
                    pgid="pgtrigger_update_feature_dtype_on_record_type_name_change_28a83",
                    table="lamindb_record",
                    when="AFTER",
                ),
            ),
        ),
    ]
