# Generated by Django 5.2.8 on 2025-11-23 11:02

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0146_squashed"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="record",
            trigger=pgtrigger.compiler.Trigger(
                name="update_feature_dtype_on_record_type_name_change",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."name" IS DISTINCT FROM (NEW."name") AND NEW."is_type")',
                    func="WITH RECURSIVE old_record_path AS (\n    -- Start with OLD values directly, don't query the table\n    SELECT\n        OLD.id as id,\n        OLD.name as name,\n        OLD.type_id as type_id,\n        OLD.name::TEXT AS path,\n        1 as depth\n        \n    UNION ALL\n    \n    SELECT\n        r.id,\n        r.name,\n        r.type_id,\n        r.name || '[' || rp.path AS path,\n        rp.depth + 1\n    FROM lamindb_record r\n    INNER JOIN old_record_path rp ON r.id = rp.type_id\n),\npaths AS (\n    SELECT \n        path as old_path,\n        REPLACE(path, OLD.name, NEW.name) as new_path\n    FROM old_record_path \n    ORDER BY depth DESC \n    LIMIT 1\n)\nUPDATE lamindb_feature\nSET dtype = REPLACE(dtype, paths.old_path, paths.new_path)\nFROM paths\nWHERE dtype LIKE '%cat[Record[%'\n  AND dtype LIKE '%' || paths.old_path || '%';\n\nRETURN NEW;\n",
                    hash="7e63d94f3ae80c1c7e23f6c688223e60adeeae2a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_feature_dtype_on_record_type_name_change_28a83",
                    table="lamindb_record",
                    when="AFTER",
                ),
            ),
        ),
    ]
