# Generated by Django 5.2.8 on 2025-11-23 10:17

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0146_squashed"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="record",
            trigger=pgtrigger.compiler.Trigger(
                name="update_feature_dtype_on_record_type_name_change",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."name" IS DISTINCT FROM (NEW."name") AND NEW."is_type")',
                    func="DECLARE\n    old_path TEXT;\n    new_path TEXT;\nBEGIN\n    RAISE NOTICE 'Trigger fired: OLD.name=%, NEW.name=%, OLD.is_type=%', OLD.name, NEW.name, OLD.is_type;\n    \n    -- Build the hierarchical path for OLD name\n    WITH RECURSIVE record_path AS (\n        SELECT\n            id,\n            name,\n            type_id,\n            name::TEXT AS path,\n            1 as depth\n        FROM lamindb_record\n        WHERE id = OLD.id\n\n        UNION ALL\n\n        SELECT\n            r.id,\n            r.name,\n            r.type_id,\n            r.name || '[' || rp.path || ']' AS path,\n            rp.depth + 1\n        FROM lamindb_record r\n        INNER JOIN record_path rp ON r.id = rp.type_id\n    )\n    SELECT path INTO old_path\n    FROM record_path\n    ORDER BY depth DESC\n    LIMIT 1;\n\n    -- Build the hierarchical path for NEW name\n    WITH RECURSIVE record_path AS (\n        SELECT\n            id,\n            name,\n            type_id,\n            name::TEXT AS path,\n            1 as depth\n        FROM lamindb_record\n        WHERE id = NEW.id\n\n        UNION ALL\n\n        SELECT\n            r.id,\n            r.name,\n            r.type_id,\n            r.name || '[' || rp.path || ']' AS path,\n            rp.depth + 1\n        FROM lamindb_record r\n        INNER JOIN record_path rp ON r.id = rp.type_id\n    )\n    SELECT path INTO new_path\n    FROM record_path\n    ORDER BY depth DESC\n    LIMIT 1;\n\n    RAISE NOTICE 'Paths: old_path=%, new_path=%', old_path, new_path;\n    \n    -- Debug: Check what we're looking for\n    RAISE NOTICE 'Searching for pattern: cat[Record[%]]', old_path;\n    \n    -- Update feature dtypes - Case 1\n    UPDATE lamindb_feature\n    SET dtype = REPLACE(dtype, 'cat[Record[' || old_path || ']', 'cat[Record[' || new_path || ']')\n    WHERE dtype LIKE '%cat[Record[%'\n        AND (\n            dtype LIKE '%cat[Record[' || old_path || ']]%'\n            OR dtype LIKE '%cat[Record[%[' || old_path || ']]%'\n        );\n    \n    RAISE NOTICE 'Case 1 updated % rows', FOUND;\n\n    -- Update feature dtypes - Case 2\n    UPDATE lamindb_feature\n    SET dtype = REPLACE(dtype, 'cat[Record[' || old_path || '[', 'cat[Record[' || new_path || '[')\n    WHERE dtype LIKE '%cat[Record[%'\n        AND (\n            dtype LIKE '%cat[Record[' || old_path || '[%'\n            OR dtype LIKE '%cat[Record[%[' || old_path || '[%'\n        );\n    \n    RAISE NOTICE 'Case 2 updated % rows', FOUND;\n\n    RETURN NEW;\nEND;\n",
                    hash="ad37da7c2b9215fd63d0bc1201706a534480b13a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_feature_dtype_on_record_type_name_change_28a83",
                    table="lamindb_record",
                    when="AFTER",
                ),
            ),
        ),
    ]
