# Generated by Django 5.2.8 on 2025-11-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lamindb",
            "0147_record_update_feature_dtype_on_record_type_name_change_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="params",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="params",
            field=models.JSONField(null=True),
        ),
    ]
