# Generated by Django 5.2.8 on 2025-12-02 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "lamindb",
            "0149_ulabel_update_feature_dtype_on_ulabel_type_name_change_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="params",
            new_name="extra_data",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="params",
        ),
    ]
