# Generated by Django 5.2.8 on 2025-12-07 09:53

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import connection, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0150_rename_params_record_extra_data_and_more"),
    ]

    operations = []  # type: ignore


if connection.vendor == "postgresql":
    Migration.operations += [
        pgtrigger.migrations.AddTrigger(
            model_name="feature",
            trigger=pgtrigger.compiler.Trigger(
                name="update_feature_on_name_change",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.name IS DISTINCT FROM NEW.name)",
                    func="DECLARE\n    old_renamed JSONB;\n    new_renamed JSONB;\n    ts TEXT;\nBEGIN\n    -- Only proceed if name actually changed\n    IF OLD.name IS DISTINCT FROM NEW.name THEN\n        -- Update synonyms\n        IF NEW.synonyms IS NULL OR NEW.synonyms = '' THEN\n            NEW.synonyms := OLD.name;\n        ELSIF position(OLD.name in NEW.synonyms) = 0 THEN\n            NEW.synonyms := NEW.synonyms || '|' || OLD.name;\n        END IF;\n\n        -- Update _aux with rename history\n        ts := TO_CHAR(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS\"Z\"');\n\n        -- Get existing renamed history or initialize empty object\n        old_renamed := COALESCE((OLD._aux->>'renamed')::JSONB, '{}'::JSONB);\n\n        -- Add old name with timestamp\n        new_renamed := old_renamed || jsonb_build_object(ts, OLD.name);\n\n        -- Update _aux with new renamed history\n        IF NEW._aux IS NULL THEN\n            NEW._aux := jsonb_build_object('renamed', new_renamed);\n        ELSE\n            NEW._aux := NEW._aux || jsonb_build_object('renamed', new_renamed);\n        END IF;\n    END IF;\n\n    RETURN NEW;\nEND;\n",
                    hash="5f2e7a65e42c34b0455f0840def52f078726e401",
                    operation="UPDATE",
                    pgid="pgtrigger_update_feature_on_name_change_6c32d",
                    table="lamindb_feature",
                    when="BEFORE",
                ),
            ),
        ),
    ]
