# Generated by Django 5.2.8 on 2025-12-21 11:28

from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0151_feature_update_feature_on_name_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="entrypoint",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255, null=True
            ),
        ),
    ]
