# Generated by Django 5.2.8 on 2025-12-11 16:50

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import connection, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0151_feature_update_feature_on_name_change"),
    ]

    operations = []  # type: ignore


if connection.vendor == "postgresql":
    Migration.operations += [
        pgtrigger.migrations.AddTrigger(
            model_name="feature",
            trigger=pgtrigger.compiler.Trigger(
                name="prevent_feature_dtype_mutation",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.dtype IS DISTINCT FROM NEW.dtype)",
                    func="BEGIN\n    -- Prevent dtype from being changed\n    IF OLD.dtype IS DISTINCT FROM NEW.dtype THEN\n        -- Allow updates from Record triggers that maintain dtype consistency\n        -- These triggers update dtype when Record type names/hierarchies change\n        IF TG_OP = 'UPDATE' AND TG_TABLE_NAME = 'lamindb_feature' THEN\n            -- If this is a cross-table trigger update (from lamindb_record triggers),\n            -- the statement will have been initiated by a Record update\n            -- We detect this by checking if we're in a nested trigger context\n            IF pg_trigger_depth() > 1 THEN\n                RETURN NEW;\n            END IF;\n        END IF;\n        \n        RAISE EXCEPTION 'dtype field is immutable and cannot be changed'\n            USING ERRCODE = 'integrity_constraint_violation';\n    END IF;\n    \n    RETURN NEW;\nEND;\n",
                    hash="c02888594dff6795e06a19c7f21ff63d006a53f0",
                    operation="UPDATE",
                    pgid="pgtrigger_prevent_feature_dtype_mutation_dfd3d",
                    table="lamindb_feature",
                    when="BEFORE",
                ),
            ),
        ),
    ]
