# Generated by Django 5.2.8 on 2026-01-02 14:08

from typing import get_args

from django.db import migrations

import lamindb.base.fields


def copy_dtype_to_dtype_str(apps, schema_editor):
    """Copy dtype to dtype_str and convert nested Record/ULabel types to uid format."""
    # First, bulk copy all dtype values to dtype_str using raw SQL
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE lamindb_feature SET dtype_str = dtype WHERE dtype IS NOT NULL"
        )

    # Now handle the conversions for nested Record/ULabel types
    Feature = apps.get_model("lamindb", "Feature")

    # Patterns to look for
    patterns = [
        "cat[Record[",
        "cat[ULabel[",
        "list[cat[Record[",
        "list[cat[ULabel[",
    ]

    # Get all features that need conversion
    features_to_convert = []
    for pattern in patterns:
        features_to_convert.extend(
            Feature.objects.using(db_alias).filter(dtype_str__startswith=pattern)
        )

    # Convert each feature
    for feature in features_to_convert:
        try:
            # Get the dtype_as_object which should resolve to the actual record(s)
            dtype_obj = feature.dtype_as_object

            # Handle the conversion based on the dtype structure
            new_dtype_str = convert_dtype_to_uid_format(feature.dtype_str, dtype_obj)

            if new_dtype_str != feature.dtype_str:
                feature.dtype_str = new_dtype_str
                feature.save(update_fields=["dtype_str"])

        except Exception as e:
            # If conversion fails, keep the original dtype_str value
            print(
                f"Warning: Could not convert dtype for feature {feature.name} ({feature.uid}) because of error: {e}"
            )
            continue


def convert_dtype_to_uid_format(dtype_str, dtype_obj):
    """Convert dtype string with nested types to uid format.

    Args:
        dtype_str: Original dtype string like "cat[Record[LabA[Experiment]]]"
        dtype_obj: The resolved dtype object from dtype_as_object

    Returns:
        Converted dtype string like "cat[Record[uid123]]"
    """
    # Handle list types
    is_list = dtype_str.startswith("list[")
    if is_list:
        # Remove list wrapper temporarily
        inner_dtype = dtype_str[5:-1]  # Remove "list[" and "]"
        if hasattr(dtype_obj, "__origin__") and dtype_obj.__origin__ is list:
            # Get the inner type from list[T]
            dtype_obj = get_args(dtype_obj)[0]
    else:
        inner_dtype = dtype_str

    # Check if it's a union type (contains |)
    if "|" in inner_dtype:
        # Handle union types: cat[Record[...]]|ULabel[...]]
        inner_dtype = inner_dtype[4:-1]  # Remove "cat[" and "]"
        parts = inner_dtype.split("|")

        # dtype_obj should be a list for union types
        if not isinstance(dtype_obj, list):
            dtype_obj = [dtype_obj]

        converted_parts = []
        for part, obj in zip(parts, dtype_obj):
            if part.startswith("Record[") or part.startswith("ULabel["):
                registry_name = part.split("[")[0]
                if hasattr(obj, "uid"):
                    converted_parts.append(f"{registry_name}[{obj.uid}]")
                else:
                    converted_parts.append(part)
            else:
                converted_parts.append(part)

        result = f"cat[{'|'.join(converted_parts)}]"
    else:
        # Single categorical type
        if inner_dtype.startswith("cat[Record[") or inner_dtype.startswith(
            "cat[ULabel["
        ):
            # Extract registry name (Record or ULabel)
            registry_name = inner_dtype[4:].split("[")[
                0
            ]  # Remove "cat[" and get registry name
            result = f"cat[{registry_name}[{dtype_obj.uid}]]"
        else:
            result = inner_dtype

    # Re-add list wrapper if needed
    if is_list:
        result = f"list[{result}]"

    return result


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0152_run_entrypoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="dtype_str",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.RunPython(copy_dtype_to_dtype_str),
    ]
