# Generated by Django 5.2.8 on 2026-01-02 14:08

from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0152_run_entrypoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="_dtype_str",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255, null=True
            ),
        ),
    ]
