# Generated by Django 5.2.8 on 2026-01-02 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0152_run_entrypoint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="dtype",
            new_name="_dtype_str",
        ),
    ]
