# Generated by Django 5.2.8 on 2026-01-02 14:08

from django.db import migrations

from lamindb.models.feature import migrate_dtype_to_uid_format


def copy_dtype_to_dtype_str(apps, schema_editor):
    """Update _dtype_str for nested Record/ULabel types to uid format."""
    migrate_dtype_to_uid_format(schema_editor.connection, input_field="_dtype_str")


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0153_feature_dtype_str"),
    ]

    operations = [
        migrations.RunPython(copy_dtype_to_dtype_str),
    ]
