# Generated by Django 5.2.8 on 2026-01-02 14:08

from django.db import migrations

import lamindb as ln
from lamindb.models.feature import dtype_as_object, serialize_dtype


def copy_dtype_to_dtype_str(apps, schema_editor):
    """Update _dtype_str for nested Record/ULabel types to uid format."""
    # Patterns to look for old format (name-based)
    patterns = [
        "cat[Record[",
        "cat[ULabel[",
        "list[cat[Record[",
        "list[cat[ULabel[",
    ]

    # Get all features that need conversion
    features_to_convert = []
    for pattern in patterns:
        features_to_convert.extend(
            ln.Feature.objects.filter(_dtype_str__startswith=pattern)
        )

    # Convert each feature
    for feature in features_to_convert:
        try:
            # Convert old format string to objects, then serialize to UID format
            dtype_objects = dtype_as_object(feature._dtype_str, old_format=True)
            new_dtype_str = serialize_dtype(dtype_objects)

            if new_dtype_str != feature._dtype_str:
                feature._dtype_str = new_dtype_str
                feature.save(update_fields=["_dtype_str"])

        except Exception as e:
            # If conversion fails, keep the original _dtype_str value
            print(
                f"Warning: Could not convert dtype for feature {feature.name} ({feature.uid}) because of error: {e}"
            )
            continue


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0153_feature_dtype_str"),
    ]

    operations = [
        migrations.RunPython(copy_dtype_to_dtype_str),
    ]
