# Generated by Django 5.2 on 2026-01-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0154_feature_dtype_str_migrate_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="artifacts",
            field=models.ManyToManyField(
                related_name="runs",
                through="lamindb.ArtifactRun",
                to="lamindb.artifact",
            ),
        ),
    ]
