# Generated by Django 5.2 on 2026-01-02 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0154_feature_dtype_str_migrate_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="dtype_str",
            new_name="_dtype_str",
        ),
    ]
