# Generated by Django 5.2 on 2026-01-04 20:00

import django.db.models.deletion
from django.db import migrations, models

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0155_alter_artifact_artifacts_alter_run_artifacts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="components",
            new_name="linked_records",
        ),
        migrations.AlterField(
            model_name="record",
            name="linked_records",
            field=models.ManyToManyField(
                related_name="linked_in_records",
                through="lamindb.RecordRecord",
                to="lamindb.record",
            ),
        ),
        migrations.AlterField(
            model_name="schemacomponent",
            name="component",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="links_composite",
                to="lamindb.schema",
            ),
        ),
        migrations.AlterField(
            model_name="schemacomponent",
            name="composite",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links_component",
                to="lamindb.schema",
            ),
        ),
    ]
