# Generated by Django 5.2 on 2026-01-04 21:16

from django.db import migrations

from lamindb.models.feature import migrate_dtype_to_uid_format


def migrate_dtype_if_exists(apps, schema_editor):
    """Migrate dtype field to _dtype_str if dtype column exists."""
    connection = schema_editor.connection

    if connection.vendor == "sqlite":
        return

    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = 'lamindb_feature' AND column_name = 'dtype'
        """)

        if cursor.fetchone():
            # Column exists, migrate it
            migrate_dtype_to_uid_format(schema_editor.connection, input_field="dtype")


def remove_dtype_if_exists(apps, schema_editor):
    """Remove dtype field only if it exists."""
    from django.db import connection

    if connection.vendor == "sqlite":
        return

    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = 'lamindb_feature' AND column_name = 'dtype'
        """)

        if cursor.fetchone():
            # Column exists, remove it
            cursor.execute("ALTER TABLE lamindb_feature DROP COLUMN dtype CASCADE")


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0156_rename_record_components_record_linked_records_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_dtype_if_exists),
        migrations.RunPython(remove_dtype_if_exists),
        migrations.RemoveField(
            model_name="feature",
            name="_curation",
        ),
        migrations.RemoveField(
            model_name="feature",
            name="proxy_dtype",
        ),
        migrations.RenameField(
            model_name="schema",
            old_name="dtype",
            new_name="_dtype_str",
        ),
        migrations.RemoveField(
            model_name="schema",
            name="_curation",
        ),
        migrations.RemoveField(
            model_name="schema",
            name="composite",
        ),
        migrations.RemoveField(
            model_name="schema",
            name="slot",
        ),
        migrations.RemoveField(
            model_name="schema",
            name="validated_by",
        ),
    ]
