# Generated by Django 5.2 on 2026-01-04 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0157_big_changes_feature_and_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="_expect_many",
        ),
    ]
