# Generated by Django 5.2 on 2026-01-04 22:28

from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0157_big_changes_feature_and_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feature",
            name="_expect_many",
        ),
        migrations.AddField(
            model_name="feature",
            name="_observational_unit",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255, null=True
            ),
        ),
    ]
