# Generated by Django 5.2 on 2026-01-04 23:04

import pgtrigger.migrations
from django.db import connection, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0158_remove_feature__expect_many_and_more"),
    ]

    operations = []  # type: ignore


if connection.vendor == "postgresql":
    Migration.operations += [
        pgtrigger.migrations.RemoveTrigger(
            model_name="record",
            name="update_feature_dtype_on_record_type_name_change",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="record",
            name="update_feature_dtype_on_record_type_change",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="ulabel",
            name="update_feature_dtype_on_ulabel_type_name_change",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="ulabel",
            name="update_feature_dtype_on_ulabel_type_change",
        ),
    ]
