# Generated by Django 5.2 on 2026-01-05 00:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "lamindb",
            "0159_remove_record_update_feature_dtype_on_record_type_name_change_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="artifact",
            old_name="feature_sets",
            new_name="schemas",
        ),
    ]
