# Generated by Django 5.2 on 2026-01-05 01:51

import django.db.models.deletion
from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0160_rename_feature_sets_artifact_schemas"),
    ]

    operations = [
        # Rename the database columns from _branch_code to branch_id
        migrations.RunSQL(
            sql="ALTER TABLE lamindb_artifact RENAME COLUMN _branch_code TO branch_id;",
            reverse_sql="ALTER TABLE lamindb_artifact RENAME COLUMN branch_id TO _branch_code;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lamindb_collection RENAME COLUMN _branch_code TO branch_id;",
            reverse_sql="ALTER TABLE lamindb_collection RENAME COLUMN branch_id TO _branch_code;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lamindb_feature RENAME COLUMN _branch_code TO branch_id;",
            reverse_sql="ALTER TABLE lamindb_feature RENAME COLUMN branch_id TO _branch_code;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lamindb_featurevalue RENAME COLUMN _branch_code TO branch_id;",
            reverse_sql="ALTER TABLE lamindb_featurevalue RENAME COLUMN branch_id TO _branch_code;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lamindb_project RENAME COLUMN _branch_code TO branch_id;",
            reverse_sql="ALTER TABLE lamindb_project RENAME COLUMN branch_id TO _branch_code;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lamindb_record RENAME COLUMN _branch_code TO branch_id;",
            reverse_sql="ALTER TABLE lamindb_record RENAME COLUMN branch_id TO _branch_code;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lamindb_reference RENAME COLUMN _branch_code TO branch_id;",
            reverse_sql="ALTER TABLE lamindb_reference RENAME COLUMN branch_id TO _branch_code;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lamindb_run RENAME COLUMN _branch_code TO branch_id;",
            reverse_sql="ALTER TABLE lamindb_run RENAME COLUMN branch_id TO _branch_code;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lamindb_schema RENAME COLUMN _branch_code TO branch_id;",
            reverse_sql="ALTER TABLE lamindb_schema RENAME COLUMN branch_id TO _branch_code;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lamindb_storage RENAME COLUMN _branch_code TO branch_id;",
            reverse_sql="ALTER TABLE lamindb_storage RENAME COLUMN branch_id TO _branch_code;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lamindb_transform RENAME COLUMN _branch_code TO branch_id;",
            reverse_sql="ALTER TABLE lamindb_transform RENAME COLUMN branch_id TO _branch_code;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE lamindb_ulabel RENAME COLUMN _branch_code TO branch_id;",
            reverse_sql="ALTER TABLE lamindb_ulabel RENAME COLUMN branch_id TO _branch_code;",
        ),
        # Update Django's state to reflect the new db_column
        migrations.AlterField(
            model_name="artifact",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="featurevalue",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="schema",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="ulabel",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
    ]
