# Generated by Django 5.2 on 2026-01-05 01:51

import django.db.models.deletion
from django.db import migrations

import lamindb.base.fields


def rename_branch_columns(apps, schema_editor):
    """Rename _branch_code to branch_id across all models."""
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            tables = [
                "lamindb_artifact",
                "lamindb_collection",
                "lamindb_feature",
                "lamindb_featurevalue",
                "lamindb_project",
                "lamindb_record",
                "lamindb_reference",
                "lamindb_run",
                "lamindb_schema",
                "lamindb_storage",
                "lamindb_transform",
                "lamindb_ulabel",
            ]
            for table in tables:
                cursor.execute(
                    f"ALTER TABLE {table} RENAME COLUMN _branch_code TO branch_id;"
                )

    elif schema_editor.connection.vendor == "sqlite":
        # For SQLite, we need to use Django's schema editor which handles the table recreation
        # We'll do this by creating a temporary field and swapping
        pass  # Django's AlterField will handle this via table recreation


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0160_rename_feature_sets_artifact_schemas"),
    ]

    operations = [
        # For PostgreSQL: rename columns directly
        # For SQLite: this is a no-op, AlterField will handle it
        migrations.RunPython(rename_branch_columns),
        # Update Django's state - this will trigger table recreation on SQLite
        migrations.AlterField(
            model_name="artifact",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="featurevalue",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="schema",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="transform",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="ulabel",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
    ]
