# Generated by Django 5.2 on 2026-01-05 01:51

import django.db.models.deletion
from django.db import migrations

import lamindb.base.fields


def rename_branch_columns(apps, schema_editor):
    """Rename _branch_code to branch_id across all models."""
    tables = [
        "lamindb_artifact",
        "lamindb_collection",
        "lamindb_feature",
        "lamindb_featurevalue",
        "lamindb_project",
        "lamindb_record",
        "lamindb_reference",
        "lamindb_run",
        "lamindb_schema",
        "lamindb_storage",
        "lamindb_transform",
        "lamindb_ulabel",
    ]

    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == "postgresql":
            for table in tables:
                cursor.execute(
                    f"ALTER TABLE {table} RENAME COLUMN _branch_code TO branch_id;"
                )

        elif schema_editor.connection.vendor == "sqlite":
            # SQLite 3.25.0+ supports ALTER TABLE RENAME COLUMN
            for table in tables:
                try:
                    cursor.execute(
                        f"ALTER TABLE {table} RENAME COLUMN _branch_code TO branch_id;"
                    )
                except Exception as error:
                    raise NotImplementedError(
                        "This migration requires SQLite 3.25.0 or newer. "
                        "Please upgrade SQLite or manually recreate the tables."
                    ) from error


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0160_rename_feature_sets_artifact_schemas"),
    ]

    operations = [
        # Rename the columns at the database level
        migrations.RunPython(
            rename_branch_columns,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="artifactartifact",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactartifact",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactproject",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactproject",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactrecord",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactrecord",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactreference",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactreference",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactrun",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactrun",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactulabel",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactulabel",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactuser",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactuser",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="collectionrecord",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="collectionrecord",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="collectionulabel",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="collectionulabel",
            name="label_ref_is_name",
        ),
        # Update Django's state only (no database operations)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="artifact",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="collection",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="feature",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="featurevalue",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="project",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="record",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="reference",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="run",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="schema",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="storage",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="transform",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
                migrations.AlterField(
                    model_name="ulabel",
                    name="branch",
                    field=lamindb.base.fields.ForeignKey(
                        blank=True,
                        db_column="branch_id",
                        db_default=1,
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lamindb.branch",
                    ),
                ),
            ],
        ),
    ]
