# Generated by Django 5.2 on 2026-01-06

from django.db import migrations, models


def rename_m2m_tables(apps, schema_editor):
    """Rename the ManyToMany tables for _subsequent_runs to recreating_runs."""
    tables_to_rename = [
        ("lamindb_artifact__previous_runs", "lamindb_artifact_recreating_runs"),
        ("lamindb_collection__previous_runs", "lamindb_collection_recreating_runs"),
    ]

    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name in tables_to_rename:
            cursor.execute(f"ALTER TABLE {old_name} RENAME TO {new_name};")


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0161_rename_branch_code_to_branch_id"),
    ]

    operations = [
        # Rename the tables at the database level
        migrations.RunPython(
            rename_m2m_tables,
            migrations.RunPython.noop,
        ),
        # Update Django's state only (no database operations)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name="artifact",
                    old_name="_subsequent_runs",
                    new_name="recreating_runs",
                ),
                migrations.AlterField(
                    model_name="artifact",
                    name="recreating_runs",
                    field=models.ManyToManyField(
                        related_name="recreated_artifacts",
                        to="lamindb.run",
                    ),
                ),
                migrations.RenameField(
                    model_name="collection",
                    old_name="_subsequent_runs",
                    new_name="recreating_runs",
                ),
                migrations.AlterField(
                    model_name="collection",
                    name="recreating_runs",
                    field=models.ManyToManyField(
                        related_name="recreated_collections",
                        to="lamindb.run",
                    ),
                ),
            ],
        ),
    ]
