# Generated by Django 5.2 on 2026-01-05 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0161_alter_artifact_branch_alter_collection_branch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artifactartifact",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactartifact",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactproject",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactproject",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactrecord",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactrecord",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactreference",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactreference",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactrun",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactrun",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactulabel",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactulabel",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactuser",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="artifactuser",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="collectionrecord",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="collectionrecord",
            name="label_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="collectionulabel",
            name="feature_ref_is_name",
        ),
        migrations.RemoveField(
            model_name="collectionulabel",
            name="label_ref_is_name",
        ),
    ]
