# Generated by Django 5.2 on 2026-01-07 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0162_rename_subsequent_runs_to_recreating_runs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artifact",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="artifactblock",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="branchblock",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="collection",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="collectionblock",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="featureblock",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="projectblock",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="recordblock",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="rootblock",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="runblock",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="schemablock",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="spaceblock",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="transform",
            old_name="version",
            new_name="version_tag",
        ),
        migrations.RenameField(
            model_name="transformblock",
            old_name="version",
            new_name="version_tag",
        ),
    ]
