# Generated by Django 5.2 on 2026-01-07 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0163_rename_version_artifact_vtag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transform",
            old_name="type",
            new_name="kind",
        ),
        migrations.RemoveField(
            model_name="run",
            name="_logfile",
        ),
        migrations.RemoveField(
            model_name="transform",
            name="_template",
        ),
    ]
