# Generated by Django 5.2 on 2026-01-07 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0164_rename_type_transform_kind_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FeatureValue",
            new_name="JsonValue",
        ),
        migrations.RenameModel(
            old_name="ArtifactFeatureValue",
            new_name="ArtifactJsonValue",
        ),
        migrations.RenameModel(
            old_name="RunFeatureValue",
            new_name="RunJsonValue",
        ),
    ]
