# Generated by Django 5.2 on 2026-01-07 17:35

import django.db.models.deletion
from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0165_alter_runfeaturevalue_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artifactjsonvalue",
            old_name="featurevalue",
            new_name="jsonvalue",
        ),
        migrations.RenameField(
            model_name="runjsonvalue",
            old_name="featurevalue",
            new_name="jsonvalue",
        ),
        migrations.AlterUniqueTogether(
            name="artifactjsonvalue",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="runjsonvalue",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="artifactjsonvalue",
            name="artifact",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links_jsonvalue",
                to="lamindb.artifact",
            ),
        ),
        migrations.AlterField(
            model_name="runjsonvalue",
            name="run",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links_jsonvalue",
                to="lamindb.run",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="artifactjsonvalue",
            unique_together={("artifact", "jsonvalue")},
        ),
        migrations.AlterUniqueTogether(
            name="runjsonvalue",
            unique_together={("run", "jsonvalue")},
        ),
        migrations.RenameField(
            model_name="artifact",
            old_name="_feature_values",
            new_name="json_values",
        ),
        migrations.RenameField(
            model_name="run",
            old_name="_feature_values",
            new_name="json_values",
        ),
    ]
