# Generated by Django 5.2 on 2026-01-07 18:00

import django.db.models.deletion
from django.db import migrations, models

import lamindb


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0166_rename_featurevalue_artifactjsonvalue_jsonvalue_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artifactblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="branchblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="collectionblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="featureblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="projectblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="recordblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="rootblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="runblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="schemablock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="spaceblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="transformblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="rootblock",
            old_name="name",
            new_name="context",
        ),
        migrations.RemoveField(
            model_name="artifactblock",
            name="vertical_pos",
        ),
        migrations.RemoveField(
            model_name="branchblock",
            name="vertical_pos",
        ),
        migrations.RemoveField(
            model_name="collectionblock",
            name="vertical_pos",
        ),
        migrations.RemoveField(
            model_name="featureblock",
            name="vertical_pos",
        ),
        migrations.RemoveField(
            model_name="projectblock",
            name="vertical_pos",
        ),
        migrations.RemoveField(
            model_name="recordblock",
            name="vertical_pos",
        ),
        migrations.RemoveField(
            model_name="rootblock",
            name="vertical_pos",
        ),
        migrations.RemoveField(
            model_name="runblock",
            name="vertical_pos",
        ),
        migrations.RemoveField(
            model_name="schemablock",
            name="vertical_pos",
        ),
        migrations.RemoveField(
            model_name="spaceblock",
            name="vertical_pos",
        ),
        migrations.RemoveField(
            model_name="transformblock",
            name="vertical_pos",
        ),
        migrations.AddField(
            model_name="artifactblock",
            name="_aux",
            field=models.JSONField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="branchblock",
            name="_aux",
            field=models.JSONField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="collectionblock",
            name="_aux",
            field=models.JSONField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="featureblock",
            name="_aux",
            field=models.JSONField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="projectblock",
            name="_aux",
            field=models.JSONField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="recordblock",
            name="_aux",
            field=models.JSONField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="rootblock",
            name="_aux",
            field=models.JSONField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="rootblock",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_column="branch_id",
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AddField(
            model_name="rootblock",
            name="is_locked",
            field=lamindb.base.fields.BooleanField(
                blank=True, db_default=False, default=False
            ),
        ),
        migrations.AddField(
            model_name="rootblock",
            name="space",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.space",
            ),
        ),
        migrations.AddField(
            model_name="runblock",
            name="_aux",
            field=models.JSONField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="schemablock",
            name="_aux",
            field=models.JSONField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="spaceblock",
            name="_aux",
            field=models.JSONField(db_default=None, default=None, null=True),
        ),
        migrations.AddField(
            model_name="transformblock",
            name="_aux",
            field=models.JSONField(db_default=None, default=None, null=True),
        ),
        migrations.RunSQL(
            sql=[
                "UPDATE lamindb_feature SET is_type = FALSE WHERE is_type IS NULL;",
                "UPDATE lamindb_reference SET is_type = FALSE WHERE is_type IS NULL;",
                "UPDATE lamindb_schema SET is_type = FALSE WHERE is_type IS NULL;",
                "UPDATE lamindb_ulabel SET is_type = FALSE WHERE is_type IS NULL;",
                "UPDATE lamindb_project SET is_type = FALSE WHERE is_type IS NULL;",
            ],
        ),
    ]
