# Generated by Django 5.2 on 2026-01-07 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0166_rename_featurevalue_artifactjsonvalue_jsonvalue_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artifactblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="branchblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="collectionblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="featureblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="projectblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="recordblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="rootblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="runblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="schemablock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="spaceblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="transformblock",
            old_name="type",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="rootblock",
            old_name="name",
            new_name="context",
        ),
    ]
