# Generated by Django 5.2 on 2026-01-08 20:40

from django.db import migrations

import lamindb.base.fields


def migrate_transform_data(apps, schema_editor):
    """Migrate transform data: set key to '' if NULL, and move config to _aux."""
    Transform = apps.get_model("lamindb", "Transform")

    # Update key to '' where NULL
    Transform.objects.filter(key__isnull=True).update(key="")

    # Migrate config to _aux.config for transforms that have config data
    for transform in Transform.objects.filter(config__isnull=False).exclude(config={}):
        aux_data = transform._aux or {}
        aux_data["config"] = transform.config
        transform._aux = aux_data
        transform.save(update_fields=["_aux"])


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0169_alter_feature_is_type_alter_project_is_type_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_transform_data,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="transform",
            name="config",
        ),
        migrations.RemoveField(
            model_name="transform",
            name="flow",
        ),
        migrations.RemoveField(
            model_name="transform",
            name="is_flow",
        ),
        migrations.AlterField(
            model_name="transform",
            name="key",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=1024
            ),
        ),
    ]
