# Generated by Django 5.2 on 2026-01-09 11:02

from django.db import migrations


def migrate_save_completed_to_aux(apps, schema_editor):
    """Migrate _save_completed to _aux['storage_completed']."""
    db_vendor = schema_editor.connection.vendor

    if db_vendor == "postgresql":
        # Import lazily to avoid loading models during migration
        from lamindb.models.artifact import migrate_save_completed_to_aux_postgres

        migrate_save_completed_to_aux_postgres(schema_editor)
    # No SQLite migration needed - field was just added and likely empty


class Migration(migrations.Migration):
    dependencies = [
        (
            "lamindb",
            "0172_alter_artifact__save_completed_alter_feature_coerce_and_more",
        ),
    ]

    operations = [
        # First migrate data from _save_completed to _aux['storage_completed']
        migrations.RunPython(migrate_save_completed_to_aux, migrations.RunPython.noop),
        # Then remove the _save_completed field
        migrations.RemoveField(
            model_name="artifact",
            name="_save_completed",
        ),
    ]
