# Generated by Django 5.2 on 2026-01-09 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "lamindb",
            "0172_alter_artifact__save_completed_alter_feature_coerce_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artifact",
            name="_save_completed",
        ),
    ]
