# Generated by Django 5.2 on 2026-01-09 11:40

import django.db.models.deletion
from django.db import migrations, models


def clear_environment_fk(apps, schema_editor):
    """Clear any existing environment FK data before changing the target model."""
    Transform = apps.get_model("lamindb", "Transform")
    count = Transform.objects.filter(environment__isnull=False).update(environment=None)
    if count:
        print(f"  Cleared {count} environment references from Transform")


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0173_remove_artifact__save_completed"),
    ]

    operations = [
        migrations.RunPython(clear_environment_fk, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="transform",
            name="environment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_environment_of_transforms",
                to="lamindb.artifact",
            ),
        ),
    ]
