# Generated by Django 5.2 on 2026-01-09 12:15

from django.db import migrations

import lamindb.base.fields
import lamindb.base.uids


def remove_constraint_if_exists(apps, schema_editor):
    """Remove constraints only if they exist."""
    connection = schema_editor.connection

    # Constraints to remove from feature table
    constraints = [
        "dtype_not_null_when_is_type_false",
        "unique_feature_type_name_at_root",
        "unique_feature_type_name_under_type",
    ]

    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            for constraint_name in constraints:
                # Check if constraint exists
                cursor.execute(
                    """
                    SELECT constraint_name
                    FROM information_schema.table_constraints
                    WHERE table_name = 'lamindb_feature'
                    AND constraint_name = %s
                """,
                    [constraint_name],
                )

                if cursor.fetchone():
                    # Constraint exists, remove it
                    cursor.execute(
                        f"ALTER TABLE lamindb_feature DROP CONSTRAINT {constraint_name}"
                    )

        elif connection.vendor == "sqlite":
            # SQLite 3.35.0+ supports DROP CONSTRAINT (but not IF EXISTS)
            # Check if constraints exist first, then drop them
            cursor.execute("""
                SELECT sql
                FROM sqlite_master
                WHERE type = 'table' AND name = 'lamindb_feature'
            """)
            result = cursor.fetchone()

            if result and result[0]:
                table_sql = result[0].lower()
                for constraint_name in constraints:
                    constraint_exists = constraint_name in table_sql

                    if constraint_exists:
                        try:
                            # SQLite 3.35.0+ supports DROP CONSTRAINT
                            cursor.execute(
                                f"ALTER TABLE lamindb_feature DROP CONSTRAINT {constraint_name}"
                            )
                        except Exception:  # noqa: S110
                            # For SQLite versions < 3.35.0, DROP CONSTRAINT is not supported
                            # The constraint will be removed when Django recreates the table
                            # if needed during subsequent schema changes
                            pass


def add_constraint_if_not_exists(apps, schema_editor):
    """Add constraint only if it doesn't exist."""
    connection = schema_editor.connection
    constraint_name = "feature_dtype_str_not_null_when_is_type_false"

    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            # Check if constraint already exists
            cursor.execute(
                """
                SELECT constraint_name
                FROM information_schema.table_constraints
                WHERE table_name = 'lamindb_feature'
                AND constraint_name = %s
                """,
                [constraint_name],
            )

            if not cursor.fetchone():
                # Constraint doesn't exist, add it
                # Condition: (is_type = TRUE) OR (_dtype_str IS NOT NULL)
                cursor.execute(
                    f"""
                    ALTER TABLE lamindb_feature
                    ADD CONSTRAINT {constraint_name}
                    CHECK ((is_type = TRUE) OR (_dtype_str IS NOT NULL))
                    """
                )

        elif connection.vendor == "sqlite":
            # Check if constraint exists in table definition
            cursor.execute("""
                SELECT sql
                FROM sqlite_master
                WHERE type = 'table' AND name = 'lamindb_feature'
            """)
            result = cursor.fetchone()

            if result and result[0]:
                table_sql = result[0].lower()
                constraint_exists = constraint_name in table_sql

                if not constraint_exists:
                    # SQLite 3.35.0+ supports ADD CONSTRAINT
                    try:
                        cursor.execute(
                            f"""
                            ALTER TABLE lamindb_feature
                            ADD CONSTRAINT {constraint_name}
                            CHECK ((is_type = 1) OR (_dtype_str IS NOT NULL))
                            """
                        )
                    except Exception:  # noqa: S110
                        # For SQLite versions < 3.35.0, ADD CONSTRAINT is not supported
                        # The constraint will need to be added when table is recreated
                        pass


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0174_alter_transform_environment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RunPython(
            remove_constraint_if_exists, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_project_type_name_at_root",
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_project_type_name_under_type",
        ),
        migrations.RemoveConstraint(
            model_name="record",
            name="unique_record_type_name_at_root",
        ),
        migrations.RemoveConstraint(
            model_name="record",
            name="unique_record_type_name_under_type",
        ),
        migrations.RemoveConstraint(
            model_name="reference",
            name="unique_reference_type_name_at_root",
        ),
        migrations.RemoveConstraint(
            model_name="reference",
            name="unique_reference_type_name_under_type",
        ),
        migrations.RemoveConstraint(
            model_name="schema",
            name="unique_schema_type_name_at_root",
        ),
        migrations.RemoveConstraint(
            model_name="schema",
            name="unique_schema_type_name_under_type",
        ),
        migrations.RemoveConstraint(
            model_name="ulabel",
            name="unique_ulabel_type_name_at_root",
        ),
        migrations.RemoveConstraint(
            model_name="ulabel",
            name="unique_ulabel_type_name_under_type",
        ),
        migrations.AlterField(
            model_name="space",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                db_index=True,
                default=lamindb.base.uids.base62_12,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.RunPython(
            add_constraint_if_not_exists, reverse_code=migrations.RunPython.noop
        ),
    ]
