# Generated by Django 5.2 on 2026-01-09 12:15

from django.db import migrations, models

import lamindb.base.fields
import lamindb.base.uids


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0174_alter_transform_environment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="feature",
            name="dtype_not_null_when_is_type_false",
        ),
        migrations.RemoveConstraint(
            model_name="feature",
            name="unique_feature_type_name_at_root",
        ),
        migrations.RemoveConstraint(
            model_name="feature",
            name="unique_feature_type_name_under_type",
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_project_type_name_at_root",
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_project_type_name_under_type",
        ),
        migrations.RemoveConstraint(
            model_name="record",
            name="unique_record_type_name_at_root",
        ),
        migrations.RemoveConstraint(
            model_name="record",
            name="unique_record_type_name_under_type",
        ),
        migrations.RemoveConstraint(
            model_name="reference",
            name="unique_reference_type_name_at_root",
        ),
        migrations.RemoveConstraint(
            model_name="reference",
            name="unique_reference_type_name_under_type",
        ),
        migrations.RemoveConstraint(
            model_name="schema",
            name="unique_schema_type_name_at_root",
        ),
        migrations.RemoveConstraint(
            model_name="schema",
            name="unique_schema_type_name_under_type",
        ),
        migrations.RemoveConstraint(
            model_name="ulabel",
            name="unique_ulabel_type_name_at_root",
        ),
        migrations.RemoveConstraint(
            model_name="ulabel",
            name="unique_ulabel_type_name_under_type",
        ),
        migrations.AlterField(
            model_name="space",
            name="uid",
            field=lamindb.base.fields.CharField(
                blank=True,
                db_index=True,
                default=lamindb.base.uids.base62_12,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="feature",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_type", True), ("_dtype_str__isnull", False), _connector="OR"
                ),
                name="feature_dtype_str_not_null_when_is_type_false",
            ),
        ),
    ]
