# Generated by Django 5.2 on 2026-01-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0175_squashed"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RootBlock",
            new_name="Block",
        ),
        migrations.RenameField(
            model_name="block",
            old_name="context",
            new_name="key",
        ),
        migrations.AlterField(
            model_name="block",
            name="key",
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
