# Generated by Django 5.2 on 2026-02-15 14:12

import django.db.models.deletion
from django.db import migrations, models

import lamindb.base.fields
import lamindb.models.sqlrecord


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0178_v2_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="plans",
        ),
        migrations.CreateModel(
            name="BranchArtifact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "artifact",
                    lamindb.base.fields.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links_branch",
                        to="lamindb.artifact",
                    ),
                ),
                (
                    "branch",
                    lamindb.base.fields.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_artifact",
                        to="lamindb.branch",
                    ),
                ),
            ],
            options={
                "unique_together": {("branch", "artifact")},
            },
            bases=(models.Model, lamindb.models.sqlrecord.IsLink),
        ),
        migrations.AddField(
            model_name="branch",
            name="artifacts",
            field=models.ManyToManyField(
                related_name="linked_by_branches",
                through="lamindb.BranchArtifact",
                to="lamindb.artifact",
            ),
        ),
        migrations.DeleteModel(
            name="BranchPlan",
        ),
    ]
