# Generated by Django 5.2 on 2026-02-15 14:29

import django.db.models.deletion
from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0179_v2_2_part_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runartifact",
            name="artifact",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="links_in_run",
                to="lamindb.artifact",
            ),
        ),
        migrations.AlterField(
            model_name="runartifact",
            name="run",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values_artifact",
                to="lamindb.run",
            ),
        ),
    ]
