# Generated by Django 5.2 on 2026-02-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0180_v2_2_part_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="anchor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="lamindb.block",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="key",
            field=models.CharField(db_index=True, max_length=1024, null=True),
        ),
    ]
