# Generated by Django 5.2 on 2026-02-17 16:33

import django.db.models.deletion
from django.db import migrations, models

import lamindb.base.fields
import lamindb.base.users


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0181_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="_status_code",
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="artifactblock",
            name="created_by",
            field=models.ForeignKey(
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="artifactblock",
            name="kind",
            field=models.CharField(
                db_default="readme", db_index=True, default="readme", max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="created_by",
            field=models.ForeignKey(
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="kind",
            field=models.CharField(
                db_default="readme", db_index=True, default="readme", max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="created_by",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="branchblock",
            name="created_by",
            field=models.ForeignKey(
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="branchblock",
            name="kind",
            field=models.CharField(
                db_default="readme", db_index=True, default="readme", max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="collectionblock",
            name="created_by",
            field=models.ForeignKey(
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="collectionblock",
            name="kind",
            field=models.CharField(
                db_default="readme", db_index=True, default="readme", max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="featureblock",
            name="created_by",
            field=models.ForeignKey(
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="featureblock",
            name="kind",
            field=models.CharField(
                db_default="readme", db_index=True, default="readme", max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="projectblock",
            name="created_by",
            field=models.ForeignKey(
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="projectblock",
            name="kind",
            field=models.CharField(
                db_default="readme", db_index=True, default="readme", max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="recordblock",
            name="created_by",
            field=models.ForeignKey(
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="recordblock",
            name="kind",
            field=models.CharField(
                db_default="readme", db_index=True, default="readme", max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="runblock",
            name="created_by",
            field=models.ForeignKey(
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="runblock",
            name="kind",
            field=models.CharField(
                db_default="readme", db_index=True, default="readme", max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="schemablock",
            name="created_by",
            field=models.ForeignKey(
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="schemablock",
            name="kind",
            field=models.CharField(
                db_default="readme", db_index=True, default="readme", max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="spaceblock",
            name="created_by",
            field=models.ForeignKey(
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="spaceblock",
            name="kind",
            field=models.CharField(
                db_default="readme", db_index=True, default="readme", max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="transformblock",
            name="created_by",
            field=models.ForeignKey(
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="transformblock",
            name="kind",
            field=models.CharField(
                db_default="readme", db_index=True, default="readme", max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="ulabelblock",
            name="created_by",
            field=models.ForeignKey(
                default=lamindb.base.users.current_user_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
        migrations.AlterField(
            model_name="ulabelblock",
            name="kind",
            field=models.CharField(
                db_default="readme", db_index=True, default="readme", max_length=22
            ),
        ),
    ]
