# Generated by Django 5.2 on 2026-02-17 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0182_squashed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="artifacts",
        ),
        migrations.DeleteModel(
            name="BranchArtifact",
        ),
    ]
