# Generated by Django 5.2 on 2026-03-07 12:16

import django.db.models.deletion
from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0183_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transformrecord",
            name="feature",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="links_transformrecord",
                to="lamindb.feature",
            ),
        ),
    ]
