# Generated by Django 5.2 on 2026-04-05 14:32

import django.db.models.deletion
from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0184_alter_transformrecord_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runrecord",
            name="feature",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="links_runrecord",
                to="lamindb.feature",
            ),
        ),
    ]
