# Generated by Django 5.2 on 2026-04-16 06:38

import django.db.models.deletion
from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0186_v2_4"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branchblock",
            name="created_on",
        ),
        migrations.AlterField(
            model_name="block",
            name="branch",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="created_on",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                db_default=1,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.branch",
            ),
        ),
    ]
