# Generated by Django 6.1 on 2026-06-05 13:49

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import connection, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0187_squashed"),
    ]
    operations = []  # type: ignore


if connection.vendor == "postgresql":
    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="record",
            name="prevent_record_type_cycle",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="record",
            trigger=pgtrigger.compiler.Trigger(
                name="prevent_record_type_cycle",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (NEW.type_id IS NOT NULL)",
                    func="\n                        -- Enforce that records typed by a single-space type stay in the same space\n                        IF EXISTS (\n                            SELECT 1\n                            FROM lamindb_record r\n                            WHERE r.id = NEW.type_id\n                              AND r._aux->>'ss' = '1'\n                              AND r.space_id IS DISTINCT FROM NEW.space_id\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: record space must match locked type space';\n                        END IF;\n\n                        -- Check for direct self-reference\n                        IF NEW.type_id = NEW.id THEN\n                            RAISE EXCEPTION 'Cannot set type: record cannot be its own type';\n                        END IF;\n\n                        -- Check for cycles in the type chain\n                        IF EXISTS (\n                            WITH RECURSIVE type_chain AS (\n                                SELECT type_id, 1 as depth\n                                FROM lamindb_record\n                                WHERE id = NEW.type_id\n\n                                UNION ALL\n\n                                SELECT r.type_id, tc.depth + 1\n                                FROM lamindb_record r\n                                INNER JOIN type_chain tc ON r.id = tc.type_id\n                                WHERE tc.depth < 100\n                            )\n                            SELECT 1 FROM type_chain WHERE type_id = NEW.id\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: would create a cycle';\n                        END IF;\n\n                        RETURN NEW;\n                    ",
                    hash="f090ccad68bba140a179ad1540951dbf6ca2504a",
                    operation="UPDATE OR INSERT",
                    pgid="pgtrigger_prevent_record_type_cycle_56c18",
                    table="lamindb_record",
                    when="BEFORE",
                ),
            ),
        ),
    ]
