# Generated by Django 6.1 on 2026-06-07 18:28

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import lamindb.base.fields
import lamindb.base.users
import lamindb.models.run


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0188_remove_record_prevent_record_type_cycle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="extra_data",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="_ounit_str",
            field=lamindb.base.fields.CharField(
                blank=True, db_index=True, default=None, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="extra_data",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="transform",
            name="run",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                default=lamindb.models.run.current_run,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="output_transforms",
                to="lamindb.run",
            ),
        ),
        migrations.AddField(
            model_name="transformtransform",
            name="run",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                default=lamindb.models.run.current_run,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.run",
            ),
        ),
        migrations.AlterField(
            model_name="transformtransform",
            name="created_at",
            field=lamindb.base.fields.DateTimeField(
                blank=True,
                db_default=django.db.models.functions.datetime.Now(),
                db_index=True,
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="transformtransform",
            name="created_by",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                default=lamindb.base.users.current_user_id,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lamindb.user",
            ),
        ),
    ]
