# Generated by Django 6.1 on 2026-06-09 20:40

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import connection, migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0189_squashed"),
    ]
    operations = []  # type: ignore


if connection.vendor == "postgresql":
    Migration.operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="feature",
            name="prevent_feature_type_cycle",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="project",
            name="prevent_project_type_cycle",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="record",
            name="prevent_record_type_cycle",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="reference",
            name="prevent_reference_type_cycle",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="schema",
            name="prevent_schema_type_cycle",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="ulabel",
            name="prevent_ulabel_type_cycle",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="feature",
            trigger=pgtrigger.compiler.Trigger(
                name="prevent_feature_type_cycle",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (NEW.type_id IS NOT NULL)",
                    func="\n                        IF EXISTS (\n                            SELECT 1\n                            FROM lamindb_feature f\n                            WHERE f.id = NEW.type_id\n                              AND (\n                                (\n                                  f._aux->>'ss' = '1'\n                                  AND f.space_id IS DISTINCT FROM NEW.space_id\n                                )\n                                OR (\n                                  f._aux ? 'ss'\n                                  AND f._aux->>'ss' <> '1'\n                                  AND NOT EXISTS (\n                                      SELECT 1\n                                      FROM lamindb_space sp\n                                      WHERE sp.uid = f._aux->>'ss'\n                                        AND sp.id = NEW.space_id\n                                  )\n                                )\n                              )\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: feature space must match single-space type space';\n                        END IF;\n\n                        -- Check for direct self-reference\n                        IF NEW.type_id = NEW.id THEN\n                            RAISE EXCEPTION 'Cannot set type: feature cannot be its own type';\n                        END IF;\n\n                        -- Check for cycles in the type chain\n                        IF EXISTS (\n                            WITH RECURSIVE type_chain AS (\n                                SELECT type_id, 1 as depth\n                                FROM lamindb_feature\n                                WHERE id = NEW.type_id\n\n                                UNION ALL\n\n                                SELECT f.type_id, tc.depth + 1\n                                FROM lamindb_feature f\n                                INNER JOIN type_chain tc ON f.id = tc.type_id\n                                WHERE tc.depth < 100\n                            )\n                            SELECT 1 FROM type_chain WHERE type_id = NEW.id\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: would create a cycle';\n                        END IF;\n\n                        RETURN NEW;\n                    ",
                    hash="f01da1680432db201311f973077a933411750c04",
                    operation="UPDATE OR INSERT",
                    pgid="pgtrigger_prevent_feature_type_cycle_04c90",
                    table="lamindb_feature",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="project",
            trigger=pgtrigger.compiler.Trigger(
                name="prevent_project_type_cycle",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (NEW.type_id IS NOT NULL)",
                    func="\n                        IF EXISTS (\n                            SELECT 1\n                            FROM lamindb_project p\n                            WHERE p.id = NEW.type_id\n                              AND (\n                                (\n                                  p._aux->>'ss' = '1'\n                                  AND p.space_id IS DISTINCT FROM NEW.space_id\n                                )\n                                OR (\n                                  p._aux ? 'ss'\n                                  AND p._aux->>'ss' <> '1'\n                                  AND NOT EXISTS (\n                                      SELECT 1\n                                      FROM lamindb_space sp\n                                      WHERE sp.uid = p._aux->>'ss'\n                                        AND sp.id = NEW.space_id\n                                  )\n                                )\n                              )\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: project space must match single-space type space';\n                        END IF;\n\n                        -- Check for direct self-reference\n                        IF NEW.type_id = NEW.id THEN\n                            RAISE EXCEPTION 'Cannot set type: project cannot be its own type';\n                        END IF;\n\n                        -- Check for cycles in the type chain\n                        IF EXISTS (\n                            WITH RECURSIVE type_chain AS (\n                                SELECT type_id, 1 as depth\n                                FROM lamindb_project\n                                WHERE id = NEW.type_id\n\n                                UNION ALL\n\n                                SELECT p.type_id, tc.depth + 1\n                                FROM lamindb_project p\n                                INNER JOIN type_chain tc ON p.id = tc.type_id\n                                WHERE tc.depth < 100\n                            )\n                            SELECT 1 FROM type_chain WHERE type_id = NEW.id\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: would create a cycle';\n                        END IF;\n\n                        RETURN NEW;\n                    ",
                    hash="3929fa76989e11afbdc960c88dd444145b7c0d09",
                    operation="UPDATE OR INSERT",
                    pgid="pgtrigger_prevent_project_type_cycle_e2567",
                    table="lamindb_project",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="record",
            trigger=pgtrigger.compiler.Trigger(
                name="prevent_record_type_cycle",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (NEW.type_id IS NOT NULL)",
                    func="\n                        -- Enforce that records typed by a single-space type stay in the same space\n                        IF EXISTS (\n                            SELECT 1\n                            FROM lamindb_record r\n                            WHERE r.id = NEW.type_id\n                              AND (\n                                (\n                                  r._aux->>'ss' = '1'\n                                  AND r.space_id IS DISTINCT FROM NEW.space_id\n                                )\n                                OR (\n                                  r._aux ? 'ss'\n                                  AND r._aux->>'ss' <> '1'\n                                  AND NOT EXISTS (\n                                      SELECT 1\n                                      FROM lamindb_space sp\n                                      WHERE sp.uid = r._aux->>'ss'\n                                        AND sp.id = NEW.space_id\n                                  )\n                                )\n                              )\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: record space must match locked type space';\n                        END IF;\n\n                        -- Check for direct self-reference\n                        IF NEW.type_id = NEW.id THEN\n                            RAISE EXCEPTION 'Cannot set type: record cannot be its own type';\n                        END IF;\n\n                        -- Check for cycles in the type chain\n                        IF EXISTS (\n                            WITH RECURSIVE type_chain AS (\n                                SELECT type_id, 1 as depth\n                                FROM lamindb_record\n                                WHERE id = NEW.type_id\n\n                                UNION ALL\n\n                                SELECT r.type_id, tc.depth + 1\n                                FROM lamindb_record r\n                                INNER JOIN type_chain tc ON r.id = tc.type_id\n                                WHERE tc.depth < 100\n                            )\n                            SELECT 1 FROM type_chain WHERE type_id = NEW.id\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: would create a cycle';\n                        END IF;\n\n                        RETURN NEW;\n                    ",
                    hash="4d494733110330433a44ecedc059ea38e934a118",
                    operation="UPDATE OR INSERT",
                    pgid="pgtrigger_prevent_record_type_cycle_56c18",
                    table="lamindb_record",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reference",
            trigger=pgtrigger.compiler.Trigger(
                name="prevent_reference_type_cycle",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (NEW.type_id IS NOT NULL)",
                    func="\n                        IF EXISTS (\n                            SELECT 1\n                            FROM lamindb_reference r\n                            WHERE r.id = NEW.type_id\n                              AND (\n                                (\n                                  r._aux->>'ss' = '1'\n                                  AND r.space_id IS DISTINCT FROM NEW.space_id\n                                )\n                                OR (\n                                  r._aux ? 'ss'\n                                  AND r._aux->>'ss' <> '1'\n                                  AND NOT EXISTS (\n                                      SELECT 1\n                                      FROM lamindb_space sp\n                                      WHERE sp.uid = r._aux->>'ss'\n                                        AND sp.id = NEW.space_id\n                                  )\n                                )\n                              )\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: reference space must match single-space type space';\n                        END IF;\n\n                        -- Check for direct self-reference\n                        IF NEW.type_id = NEW.id THEN\n                            RAISE EXCEPTION 'Cannot set type: reference cannot be its own type';\n                        END IF;\n\n                        -- Check for cycles in the type chain\n                        IF EXISTS (\n                            WITH RECURSIVE type_chain AS (\n                                SELECT type_id, 1 as depth\n                                FROM lamindb_reference\n                                WHERE id = NEW.type_id\n\n                                UNION ALL\n\n                                SELECT r.type_id, tc.depth + 1\n                                FROM lamindb_reference r\n                                INNER JOIN type_chain tc ON r.id = tc.type_id\n                                WHERE tc.depth < 100\n                            )\n                            SELECT 1 FROM type_chain WHERE type_id = NEW.id\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: would create a cycle';\n                        END IF;\n\n                        RETURN NEW;\n                    ",
                    hash="f49515130e23dfd318f91b24173cbd683ba21bd9",
                    operation="UPDATE OR INSERT",
                    pgid="pgtrigger_prevent_reference_type_cycle_3d37c",
                    table="lamindb_reference",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="schema",
            trigger=pgtrigger.compiler.Trigger(
                name="prevent_schema_type_cycle",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (NEW.type_id IS NOT NULL)",
                    func="\n                        IF EXISTS (\n                            SELECT 1\n                            FROM lamindb_schema s\n                            WHERE s.id = NEW.type_id\n                              AND (\n                                (\n                                  s._aux->>'ss' = '1'\n                                  AND s.space_id IS DISTINCT FROM NEW.space_id\n                                )\n                                OR (\n                                  s._aux ? 'ss'\n                                  AND s._aux->>'ss' <> '1'\n                                  AND NOT EXISTS (\n                                      SELECT 1\n                                      FROM lamindb_space sp\n                                      WHERE sp.uid = s._aux->>'ss'\n                                        AND sp.id = NEW.space_id\n                                  )\n                                )\n                              )\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: schema space must match single-space type space';\n                        END IF;\n\n                        -- Check for direct self-reference\n                        IF NEW.type_id = NEW.id THEN\n                            RAISE EXCEPTION 'Cannot set type: schema cannot be its own type';\n                        END IF;\n\n                        -- Check for cycles in the type chain\n                        IF EXISTS (\n                            WITH RECURSIVE type_chain AS (\n                                SELECT type_id, 1 as depth\n                                FROM lamindb_schema\n                                WHERE id = NEW.type_id\n\n                                UNION ALL\n\n                                SELECT s.type_id, tc.depth + 1\n                                FROM lamindb_schema s\n                                INNER JOIN type_chain tc ON s.id = tc.type_id\n                                WHERE tc.depth < 100\n                            )\n                            SELECT 1 FROM type_chain WHERE type_id = NEW.id\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: would create a cycle';\n                        END IF;\n\n                        RETURN NEW;\n                    ",
                    hash="6cb1488bb1c26505e3a24e9047fb4988ecb5377c",
                    operation="UPDATE OR INSERT",
                    pgid="pgtrigger_prevent_schema_type_cycle_b403c",
                    table="lamindb_schema",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="ulabel",
            trigger=pgtrigger.compiler.Trigger(
                name="prevent_ulabel_type_cycle",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (NEW.type_id IS NOT NULL)",
                    func="\n                        -- Enforce that ulabels typed by a single-space type stay in the same space\n                        IF EXISTS (\n                            SELECT 1\n                            FROM lamindb_ulabel u\n                            WHERE u.id = NEW.type_id\n                              AND (\n                                (\n                                  u._aux->>'ss' = '1'\n                                  AND u.space_id IS DISTINCT FROM NEW.space_id\n                                )\n                                OR (\n                                  u._aux ? 'ss'\n                                  AND u._aux->>'ss' <> '1'\n                                  AND NOT EXISTS (\n                                      SELECT 1\n                                      FROM lamindb_space sp\n                                      WHERE sp.uid = u._aux->>'ss'\n                                        AND sp.id = NEW.space_id\n                                  )\n                                )\n                              )\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: ulabel space must match single-space type space';\n                        END IF;\n\n                        -- Check for direct self-reference\n                        IF NEW.type_id = NEW.id THEN\n                            RAISE EXCEPTION 'Cannot set type: ulabel cannot be its own type';\n                        END IF;\n\n                        -- Check for cycles in the type chain\n                        IF EXISTS (\n                            WITH RECURSIVE type_chain AS (\n                                SELECT type_id, 1 as depth\n                                FROM lamindb_ulabel\n                                WHERE id = NEW.type_id\n\n                                UNION ALL\n\n                                SELECT r.type_id, tc.depth + 1\n                                FROM lamindb_ulabel r\n                                INNER JOIN type_chain tc ON r.id = tc.type_id\n                                WHERE tc.depth < 100\n                            )\n                            SELECT 1 FROM type_chain WHERE type_id = NEW.id\n                        ) THEN\n                            RAISE EXCEPTION 'Cannot set type: would create a cycle';\n                        END IF;\n\n                        RETURN NEW;\n                    ",
                    hash="546aa2e160857a73cb0b8a68f2941bb6f5f55031",
                    operation="UPDATE OR INSERT",
                    pgid="pgtrigger_prevent_ulabel_type_cycle_863ae",
                    table="lamindb_ulabel",
                    when="BEFORE",
                ),
            ),
        ),
    ]
