# Generated by Django 6.1 on 2026-07-07 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0190_v2_6_1"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="artifactschema",
            unique_together={("artifact", "slot", "schema"), ("artifact", "slot")},
        ),
    ]
