# Generated by Django 5.2.15 on 2026-07-18 17:57

import django.db.models.deletion
from django.db import migrations

import lamindb.base.fields


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0191_artifactschema_unique_slot_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="schema",
            field=lamindb.base.fields.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="validated_collections",
                to="lamindb.schema",
            ),
        ),
    ]
