# Generated by Django 5.2.15 on 2026-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0192_v2_9"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="artifactartifact",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artifactproject",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artifactrecord",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artifactreference",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artifactrun",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artifactulabel",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artifactuser",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="collectionrecord",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="projectrecord",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="referencerecord",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="runartifact",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="runrecord",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="transformrecord",
            unique_together=set(),
        ),
        migrations.RunSQL(
            sql="""
            -- Deduplicate rows that would violate nulls_distinct=False unique constraints.
            -- Keep the oldest row (smallest id) per pair where feature_id IS NULL.
            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY artifact_id, value_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_artifactartifact
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_artifactartifact t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;

            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY artifact_id, project_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_artifactproject
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_artifactproject t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;

            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY artifact_id, record_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_artifactrecord
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_artifactrecord t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;

            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY artifact_id, reference_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_artifactreference
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_artifactreference t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;

            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY artifact_id, run_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_artifactrun
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_artifactrun t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;

            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY artifact_id, ulabel_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_artifactulabel
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_artifactulabel t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;

            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY artifact_id, user_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_artifactuser
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_artifactuser t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;

            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY collection_id, record_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_collectionrecord
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_collectionrecord t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;

            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY project_id, record_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_projectrecord
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_projectrecord t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;

            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY reference_id, record_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_referencerecord
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_referencerecord t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;

            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY run_id, artifact_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_runartifact
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_runartifact t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;

            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY run_id, record_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_runrecord
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_runrecord t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;

            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY transform_id, record_id
                        ORDER BY id
                    ) AS rn
                FROM lamindb_transformrecord
                WHERE feature_id IS NULL
            )
            DELETE FROM lamindb_transformrecord t
            USING ranked r
            WHERE t.id = r.id AND r.rn > 1;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="artifactartifact",
            constraint=models.UniqueConstraint(
                fields=("artifact", "value", "feature"),
                name="unique_artifactartifact",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactproject",
            constraint=models.UniqueConstraint(
                fields=("artifact", "project", "feature"),
                name="unique_artifactproject",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactrecord",
            constraint=models.UniqueConstraint(
                fields=("artifact", "record", "feature"),
                name="unique_artifactrecord",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactreference",
            constraint=models.UniqueConstraint(
                fields=("artifact", "reference", "feature"),
                name="unique_artifactreference",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactrun",
            constraint=models.UniqueConstraint(
                fields=("artifact", "run", "feature"),
                name="unique_artifactrun",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactulabel",
            constraint=models.UniqueConstraint(
                fields=("artifact", "ulabel", "feature"),
                name="unique_artifactulabel",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactuser",
            constraint=models.UniqueConstraint(
                fields=("artifact", "user", "feature"),
                name="unique_artifactuser",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrecord",
            constraint=models.UniqueConstraint(
                fields=("collection", "record", "feature"),
                name="unique_collectionrecord",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="projectrecord",
            constraint=models.UniqueConstraint(
                fields=("project", "feature", "record"),
                name="unique_projectrecord",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="referencerecord",
            constraint=models.UniqueConstraint(
                fields=("reference", "feature", "record"),
                name="unique_referencerecord",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="runartifact",
            constraint=models.UniqueConstraint(
                fields=("run", "artifact", "feature"),
                name="unique_runartifact",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="runrecord",
            constraint=models.UniqueConstraint(
                fields=("run", "record", "feature"),
                name="unique_runrecord",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="transformrecord",
            constraint=models.UniqueConstraint(
                fields=("transform", "record", "feature"),
                name="unique_transformrecord",
                nulls_distinct=False,
            ),
        ),
    ]
