# Generated by Django 5.2.15 on 2026-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lamindb", "0192_v2_9"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="artifactartifact",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artifactproject",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artifactrecord",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artifactreference",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artifactrun",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artifactulabel",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="artifactuser",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="collectionrecord",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="projectrecord",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="referencerecord",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="runartifact",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="runrecord",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="transformrecord",
            unique_together=set(),
        ),
        migrations.RunSQL(
            sql="""
            -- Deduplicate rows that would violate feature IS NULL uniqueness constraints.
            -- Keep the oldest row (smallest id) per pair where feature_id IS NULL.
            DELETE FROM lamindb_artifactartifact
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_artifactartifact
                WHERE feature_id IS NULL
                GROUP BY artifact_id, value_id
              );

            DELETE FROM lamindb_artifactproject
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_artifactproject
                WHERE feature_id IS NULL
                GROUP BY artifact_id, project_id
              );

            DELETE FROM lamindb_artifactrecord
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_artifactrecord
                WHERE feature_id IS NULL
                GROUP BY artifact_id, record_id
              );

            DELETE FROM lamindb_artifactreference
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_artifactreference
                WHERE feature_id IS NULL
                GROUP BY artifact_id, reference_id
              );

            DELETE FROM lamindb_artifactrun
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_artifactrun
                WHERE feature_id IS NULL
                GROUP BY artifact_id, run_id
              );

            DELETE FROM lamindb_artifactulabel
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_artifactulabel
                WHERE feature_id IS NULL
                GROUP BY artifact_id, ulabel_id
              );

            DELETE FROM lamindb_artifactuser
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_artifactuser
                WHERE feature_id IS NULL
                GROUP BY artifact_id, user_id
              );

            DELETE FROM lamindb_collectionrecord
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_collectionrecord
                WHERE feature_id IS NULL
                GROUP BY collection_id, record_id
              );

            DELETE FROM lamindb_projectrecord
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_projectrecord
                WHERE feature_id IS NULL
                GROUP BY project_id, record_id
              );

            DELETE FROM lamindb_referencerecord
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_referencerecord
                WHERE feature_id IS NULL
                GROUP BY reference_id, record_id
              );

            DELETE FROM lamindb_runartifact
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_runartifact
                WHERE feature_id IS NULL
                GROUP BY run_id, artifact_id
              );

            DELETE FROM lamindb_runrecord
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_runrecord
                WHERE feature_id IS NULL
                GROUP BY run_id, record_id
              );

            DELETE FROM lamindb_transformrecord
            WHERE feature_id IS NULL
              AND id NOT IN (
                SELECT MIN(id)
                FROM lamindb_transformrecord
                WHERE feature_id IS NULL
                GROUP BY transform_id, record_id
              );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="artifactartifact",
            constraint=models.UniqueConstraint(
                fields=("artifact", "value", "feature"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_artifactartifact",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactartifact",
            constraint=models.UniqueConstraint(
                fields=("artifact", "value"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_artifactartifact_null_feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactproject",
            constraint=models.UniqueConstraint(
                fields=("artifact", "project", "feature"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_artifactproject",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactproject",
            constraint=models.UniqueConstraint(
                fields=("artifact", "project"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_artifactproject_null_feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactrecord",
            constraint=models.UniqueConstraint(
                fields=("artifact", "record", "feature"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_artifactrecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactrecord",
            constraint=models.UniqueConstraint(
                fields=("artifact", "record"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_artifactrecord_null_feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactreference",
            constraint=models.UniqueConstraint(
                fields=("artifact", "reference", "feature"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_artifactreference",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactreference",
            constraint=models.UniqueConstraint(
                fields=("artifact", "reference"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_artifactreference_null_feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactrun",
            constraint=models.UniqueConstraint(
                fields=("artifact", "run", "feature"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_artifactrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactrun",
            constraint=models.UniqueConstraint(
                fields=("artifact", "run"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_artifactrun_null_feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactulabel",
            constraint=models.UniqueConstraint(
                fields=("artifact", "ulabel", "feature"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_artifactulabel",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactulabel",
            constraint=models.UniqueConstraint(
                fields=("artifact", "ulabel"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_artifactulabel_null_feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactuser",
            constraint=models.UniqueConstraint(
                fields=("artifact", "user", "feature"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_artifactuser",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactuser",
            constraint=models.UniqueConstraint(
                fields=("artifact", "user"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_artifactuser_null_feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrecord",
            constraint=models.UniqueConstraint(
                fields=("collection", "record", "feature"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_collectionrecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionrecord",
            constraint=models.UniqueConstraint(
                fields=("collection", "record"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_collectionrecord_null_feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectrecord",
            constraint=models.UniqueConstraint(
                fields=("project", "feature", "record"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_projectrecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectrecord",
            constraint=models.UniqueConstraint(
                fields=("project", "record"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_projectrecord_null_feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="referencerecord",
            constraint=models.UniqueConstraint(
                fields=("reference", "feature", "record"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_referencerecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="referencerecord",
            constraint=models.UniqueConstraint(
                fields=("reference", "record"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_referencerecord_null_feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="runartifact",
            constraint=models.UniqueConstraint(
                fields=("run", "artifact", "feature"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_runartifact",
            ),
        ),
        migrations.AddConstraint(
            model_name="runartifact",
            constraint=models.UniqueConstraint(
                fields=("run", "artifact"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_runartifact_null_feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="runrecord",
            constraint=models.UniqueConstraint(
                fields=("run", "record", "feature"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_runrecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="runrecord",
            constraint=models.UniqueConstraint(
                fields=("run", "record"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_runrecord_null_feature",
            ),
        ),
        migrations.AddConstraint(
            model_name="transformrecord",
            constraint=models.UniqueConstraint(
                fields=("transform", "record", "feature"),
                condition=models.Q(("feature__isnull", False)),
                name="unique_transformrecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="transformrecord",
            constraint=models.UniqueConstraint(
                fields=("transform", "record"),
                condition=models.Q(("feature__isnull", True)),
                name="unique_transformrecord_null_feature",
            ),
        ),
    ]
