name: Propose an enhancement
description: Propose an enhancement.
body:
  - type: textarea
    id: description
    attributes:
      label: Add a description
      placeholder: |
        This is a public repository!
        Do not reveal any internal information.
    validations:
      required: true
