name: Enhancement
description: Propose an enhancement or new feature
body:
  - type: textarea
    id: description
    attributes:
      label: Enhancement
      description: Add a description
      placeholder: |
        This is a public repository!
        Do not reveal any internal information.
    validations:
      required: true
