name: Enhancement
description: Propose an enhancement or new feature
labels: []
body:
  - type: textarea
    id: description
    attributes:
      description: Add a description
      placeholder: |
        This is a public repository!
        Do not reveal any internal information.
    validations:
      required: true
